### ISSUE TITLE
Error when creating menu from template with deepness > 3

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#1403]
The following fail on window 8.1:
```javascript
require("remote").require("menu").buildFromTemplate([{
	"label":"Test1",
	"type":"submenu",
	"submenu":[{
		"label":"Test2",
		"type":"submenu",
		"submenu":[{
			"label":"Test3",
			"type":"submenu",
			"submenu":[{
				"label":"Test4"
			}]
		}]
	}]
}]);
```

with the following error:
```
Unknown type: undefined
TypeError: Unknown type: undefined
    at metaToValue (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:102:17)
    at Array.map (native)
    at unwrapArgs (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:105:17)
    at metaToValue (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:69:18)
    at metaToValue (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:75:32)
    at Array.map (native)
    at unwrapArgs (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:105:17)
    at metaToValue (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:69:18)
    at metaToValue (c:\Users\Felicien\git\TweakStyle\target\cache\atom-shell-v0.22.3-win32-ia32\resources\atom.asar\browser\lib\rpc-server.js:75:32)
    at Array.map (native)
```

**Comment by deepak1556** [comment]
@zcbenz increasing the [recursion depth](https://github.com/atom/atom-shell/blob/e98953a5a563648a69b6cb8535d1f27febeec887/atom/common/native_mate_converters/v8_value_converter.cc#L19) to higher value fixes this . Is that a suitable fix ?

**Comment by zcbenz** [comment]
> @zcbenz increasing the recursion depth to higher value fixes this . Is that a suitable fix ?

It sounds good to me.

**Comment by felicienfrancois** [comment]
What is the status of this issue ?
