### ISSUE TITLE
window building failed. bootstrap.py.

### ISSUE THREAD

**Issue by smilejp** [atom/electron#1459]
os : windows 8.1
shell : powershell
python : 2.7.9
io.js : v1.6.3

i clone code from github and python script\bootstrap.py -v command. but I got an error.
someone could help me to fix the problem??
```
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\iojs\\node.exe',
gyp verb cli   'C:\\Program Files (x86)\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@1.0.3
gyp info using node@1.6.3 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "2.7.9\r\n"
gyp verb get node dir compiling against --target node version: v0.24.0
gyp verb command install [ 'v0.24.0' ]
gyp verb install input version string "v0.24.0"
gyp verb install installing version: 0.24.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 0.24.0
gyp verb ensuring nodedir is created C:\Users\dev-1\.node-gyp\0.24.0
gyp verb created nodedir C:\Users\dev-1\.node-gyp\0.24.0
gyp http GET https://atom.io/download/atom-shell/v0.24.0/iojs-v0.24.0.tar.gz
gyp http 403 https://atom.io/download/atom-shell/v0.24.0/iojs-v0.24.0.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '0.24.0' ]
gyp verb remove using node-gyp dir: C:\Users\dev-1\.node-gyp
gyp verb remove removing target version: 0.24.0
gyp verb remove removing development files for version: 0.24.0
gyp ERR! configure error
gyp ERR! stack Error: 403 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (C:\Program Files (x86)\iojs\node_modules\npm\node_modules\node-gyp\lib\instal
l.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files (x86)\iojs\node_modules\npm\node_modules\request\reque
st.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:410:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:300:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\iojs\\node.exe" "C:\\Program Files (x86)\\iojs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Keecon\TreeLauncher\electron-src\electron\spec\node_modules\runas
gyp ERR! node -v v1.6.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm verb unsafe-perm in lifecycle true
npm info runas@2.0.0 Failed to exec install script
npm verb unlock done using C:\Users\dev-1\AppData\Roaming\npm-cache\_locks\runas-7a3b6578fa820b39.lock for C:\Keecon\Tre
eLauncher\electron-src\electron\spec\node_modules\runas
npm verb stack Error: runas@2.0.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\iojs\node_modules\npm\lib\utils\lifecycle.js:213:
16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:169:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\iojs\node_modules\npm\lib\utils\spawn.js:14:12)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:169:7)
npm verb stack     at maybeClose (child_process.js:984:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
npm verb pkgid runas@2.0.0
npm verb cwd C:\Keecon\TreeLauncher\electron-src\electron\spec
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\iojs\\node.exe" "C:\\Program Files (x86)\\iojs\\node_modules\\npm\\bin\\npm-cli.
js" "install" "--verbose"
npm ERR! node v1.6.3
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by smilejp** [comment]
found what the problem is. 
remove io.js and install node.js.
thx.
