### ISSUE TITLE
node-gyp:  Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by djohns32** [atom/electron#1529]
I am trying to convert a 64-bit node webkit project to a 64-bit electron project on a Windows 7 box.  Since electron uses iojs instead of nodejs, i assume that i need to run node-gyp from iojs.  When I do that, I get the following error:

V:\TrustedData\electron\vcxCppServiceLayer64> node-gyp clean configure build -target_arch=x64

V:\TrustedData\electron\vcxCppServiceLayer64>if not defined npm_config_node_gyp (node "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\no
de-gyp.js" clean configure build -target_arch=x64 )  else (clean configure build -target_arch=x64 )
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@1.8.1 | win32 | x64
gyp http GET https://iojs.org/dist/v1.8.1/iojs-v1.8.1.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:908:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:163:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:496:8)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "clean" "configure" "build" "-target_arch=x64"
gyp ERR! cwd V:\TrustedData\electron\vcxCppServiceLayer64
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

I was able to generate the Microsoft solution file using node-gyp from nodejs.  However, when I tried running the executable i received an error about:

V:\TrustedData\electron>electron.exe resources\vcx\vcx.js
[5544:0429/142426:ERROR:gl_surface_egl.cc(161)] eglInitialize failed with error UNKNOWN
[5544:0429/142426:ERROR:gl_surface_win.cc(163)] GLSurfaceEGL::InitializeOneOff failed.
[5544:0429/142426:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[16092:0429/142426:INFO:renderer_main.cc(212)] Renderer process started
[15408:0429/142436:INFO:CONSOLE(118)] "Uncaught Error: The specified module could not be found.
V:\TrustedData\electron\node_modules\vcx\vcxCppServiceLayer.node", source: ATOM_SHELL_ASAR.js (118)
[15408:0429/142440:INFO:CONSOLE(12)] "yui: NOT loaded: jsts-all", source: atom://V:/javascripts/yui-3.6.0/yui/build
/yui/yui-min.js (12)

Any ideas?

**Comment by mattcollier** [comment]
I'm not familiar with the errors your having,  but I have started using pangyp for all my node-gyp needs: https://www.npmjs.com/package/pangyp

**Comment by djohns32** [comment]
Matt,

Thanks for the quick response.  When I tried using pangyp, I received a similar error when it tried to download.  That turned out to be related to our strict IT policies.  I went home, installed npm, node-gyp, pangyp and ran configure to get C:\Users\david.s.johnson\.node-gyp\1.8.1.  I then brought that to work on a thumb drive.  That solved the download issue but I still get an error about "Uncaught Error: Module did not self-register."

I get "Uncaught Error: Module did not self-register."  when using pangyp or node-gyp to build the Microsoft solution file.  How do I make an app self-register?  I am using the same code from a node-webkit app.  Is there a different procedure for electron/iojs?

//-----------------------------------------------------------------------------
// Method: init
//
//  Node.js method for performing initialization
//-----------------------------------------------------------------------------

void init(Handle<Object> target) {
    Isolate* isolate = Isolate::GetCurrent();
    HandleScope scope(isolate);
    const char* method = ("vcxCppServiceLayer::init(): ");

    NODE_SET_METHOD(target, "listSystems", listSystems);

    NODE_SET_METHOD(target, "search", search);

    NODE_SET_METHOD(target, "getMetadata", getMetadata);

    NODE_SET_METHOD(target, "listOperations", listOperations);

    NODE_SET_METHOD(target, "getPublishedUncUris", getPublishedUncUris);

    NODE_SET_METHOD(target, "gxpLoadImageAndShow", gxpLoadImageAndShow);

    ApiManager::InitializeApi();

    xpl_vct_tag_mapping_initialized = false;

    // Populate the product_tables array used for controlling which VCT tables get queried and returned

    product_tables[VCX_IMAGERY].product_table_name = "products_imagery";
    product_tables[VCX_IMAGERY].query_type = CAT_QUERY_NORMAL;

    product_tables[VCX_TERRAIN].product_table_name = "products_terrain";
    product_tables[VCX_TERRAIN].query_type = CAT_QUERY_TERRAIN;

    product_tables[VCX_VIDEO].product_table_name = "products_video";
    product_tables[VCX_VIDEO].query_type = CAT_QUERY_VIDEO;

    product_tables[VCX_VECTOR].product_table_name = "products_vector";
    product_tables[VCX_VECTOR].query_type = CAT_QUERY_VECTOR;

    product_tables[VCX_REF_IMAGERY].product_table_name = "products_ref_imagery";
    product_tables[VCX_REF_IMAGERY].query_type = CAT_QUERY_REFERENCE_IMAGES;
}

NODE_MODULE(vcxCppServiceLayer, init)

Here is the error when trying to run the electron app:

V:\TrustedData\electron>StartGxpC.exe electron.bat

V:\TrustedData\electron>electron.exe resources\vcx\vcx.js
[10308:0430/095332:ERROR:gl_surface_egl.cc(161)] eglInitialize failed with error UNKNOWN
[10308:0430/095332:ERROR:gl_surface_win.cc(163)] GLSurfaceEGL::InitializeOneOff failed.
[10308:0430/095332:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[7364:0430/095332:INFO:renderer_main.cc(212)] Renderer process started
[19740:0430/095333:INFO:CONSOLE(118)] "Uncaught Error: Module did not self-register.", source: ATOM_SHELL_ASAR.js (
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: jsts-all", source: atom://V:/javascripts/yui-3.6.0/yui/build
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: jsts-all", source: atom://V:/javascripts/yui-3.6.0/yui/build
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: jsts-all", source: atom://V:/javascripts/yui-3.6.0/yui/build
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: jsts-all", source: atom://V:/javascripts/yui-3.6.0/yui/build
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: lang", source: atom://V:/javascripts/yui-3.6.0/yui/build/yui
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: array", source: atom://V:/javascripts/yui-3.6.0/yui/build/yu
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: jquery-mods", source: atom://V:/javascripts/yui-3.6.0/yui/bu
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: timeline", source: atom://V:/javascripts/yui-3.6.0/yui/build
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: datejs-all", source: atom://V:/javascripts/yui-3.6.0/yui/bui
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: jsts-all", source: atom://V:/javascripts/yui-3.6.0/yui/build
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: openlayers", source: atom://V:/javascripts/yui-3.6.0/yui/bui
[19740:0430/095335:INFO:CONSOLE(12)] "yui: NOT loaded: proj4js-compressed", source: atom://V:/javascripts/yui-3.6.0
[19740:0430/095336:INFO:CONSOLE(110)] "Uncaught TypeError: Cannot read property 'listSystems' of undefined", source
10)
[19740:0430/095337:INFO:CONSOLE(0)] "The 'overflowchanged' event is deprecated and may be removed. Please do not us
[19740:0430/095351:INFO:CONSOLE(110)] "Uncaught TypeError: Cannot read property 'listSystems' of undefined", source
10)

V:\TrustedData\electron>type electron.bat
electron.exe resources\vcx\vcx.js

StartGxpC.exe just sets some or our product specific environment variables.  Without it, I get an error that module cannot be found.  I use it, just like i do with node-webkit, when launching the app.

**Comment by djohns32** [comment]
I should have mentioned that the code above is just a snippet showing the init stuff.  I don't think that part has changed as part of converting from nodejs to iojs, right?

**Comment by mattcollier** [comment]
OK, the module did not self register I am familiar with.  On Windows, 'node' is actually a batch file that calls iojs and native modules don't like that.  You will need to copy your iojs executable to 'node' as well to satisfy native modules.

Now, I am unclear about exactly what your attempting.  But if you would like to utilize a native module from within Electron, you will need to build your native code against the Electron includes/header, not those of iojs.  You can take a look at this for an example of the syntax:

https://github.com/mattcollier/noxious/blob/0dc08e23665925f46c0b8840b6262d60d8740a19/build_win_ia32.bat

The dist-url may have changed with the project name change.

**Comment by djohns32** [comment]
Matt,

Thank you very much for your help!  The syntax that you provided was what I needed.  The 32-bit node-webkit app is now running as a 64-bit electron app.  I will mark this as closed.

Dave
