### ISSUE TITLE
window.close throws an error in child webview

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1573]
To repro:

1. Create a renderer with a WebView and a loaded page
1. Select it in elements, `$0.openDevtools()`
1. In that devtools' console, `window.close()`

![](http://cl.ly/image/0f1E2L1C3U0N/content#png)

```
Error: Cannot read property 'getId' of null
TypeError: Cannot read property 'getId' of null
  at EventEmitter.webContents.equal (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\browser\api\lib\web-contents.js:40:36)
  at Function.BrowserWindow.fromDevToolsWebContents (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\browser\api\lib\browser-window.js:159:23)
  at EventEmitter.<anonymous> (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\browser\lib\rpc-server.js:155:34)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.<anonymous> (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\browser\api\lib\web-contents.js:97:23)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

    at metaToValue (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at Object.exports.getCurrentWindow (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\renderer\api\lib\remote.js:172:26)
    at window.close (C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\renderer\lib\override.js:55:21)
    at <anonymous>:3:8
    at Object.InjectedScript._evaluateOn (<anonymous>:883:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:816:34)
    at Object.InjectedScript.evaluate (<anonymous>:682:21)
```

**Comment by zcbenz** [comment]
The webview page lost its gusetInstanceID and was treated like a normal window, I think it is caused by the same bug with #1560.
