### ISSUE TITLE
Cannot read property 'getId' of null when two developer tools are opened

### ISSUE THREAD

**Issue by zaggino** [atom/electron#1583]
I have two `BrowserWindow`s opened and developer tools for each of them, when I right click in the second one in the console (to get context menu for clearing it) I get the error below. Otherwise the window seems to work fine, I can properly debug there and execute commands. Using `electron-prebuilt@0.25.2`
```
[5254:0506/093816:ERROR:CONSOLE(77)] "Uncaught (in promise) Error: Cannot read property 'getId' of null
TypeError: Cannot read property 'getId' of null
    at EventEmitter.webContents.equal (/Users/zaggino/github/brackets-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:40:36)
    at Function.BrowserWindow.fromDevToolsWebContents (/Users/zaggino/github/brackets-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/browser-window.js:159:23)
    at EventEmitter.<anonymous> (/Users/zaggino/github/brackets-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:155:34)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Users/zaggino/github/brackets-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:97:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)", source: /Users/zaggino/github/brackets-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js (77)
```

**Comment by deepak1556** [comment]
Is the second browser window opened from the first or some other way ? I tried opening both from browser process with devtools and context menu works just fine. Is there a minimal code that can reproduce this?

**Comment by zaggino** [comment]
Yeah, the second window is opened from the first using `require.remote("brackets-window")` where it calls this `open` function: https://github.com/zaggino/brackets-electron/blob/master/app/brackets-window.js#L25-L44
I don't have minimal code to reproduce right now but I could work on one a bit later.

**Comment by zcbenz** [comment]
Closing until there is more information provided.
