### ISSUE TITLE
Error (Windows) running bootstrap.py

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#1593]
On Windows 8.1 (python 2.7.9) I immediately hit the following error after pulling the repo and attempting to run the bootstrap:

```
C:\Users\Art\Desktop\Git Repos\electron>python script\bootstrap.py -v
Running in verbose mode
git submodule sync
Traceback (most recent call last):
  File "script\bootstrap.py", line 142, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 28, in main
    update_submodules()
  File "script\bootstrap.py", line 69, in update_submodules
    execute_stdout(['git', 'submodule', 'sync'])
  File "C:\Users\Art\Desktop\Git Repos\electron\script\lib\util.py", line
 149, in execute_stdout
    subprocess.check_call(argv, env=env)
  File "C:\Python27\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Is this a problem in my Python setup, or the repo? Doing exactly the same thing on OS X worked perfectly fine.

**Comment by arthurakay** [comment]
Turns out when I installed msysgit, Git did not get added to my %PATH%.
