### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by mizchi** [atom/electron#1621]
I tried to build electron on windows 8.1

```
C:\tools\python2\python.exe C:\Users\mizchi\apps\electron\vendor\brightray\script\bootstrap --commit 07a73a610496e4a1b4f
3abc3c2fb0516187ec460 --target_arch ia32 http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent
C:\tools\python2\python.exe C:\Users\mizchi\apps\electron\script\update.py
Traceback (most recent call last):
  File "vendor\brightray\vendor\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "C:\tools\python2\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "C:\tools\python2\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", line 526, in main
    return gyp_main(args)
  File "C:\tools\python2\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", line 511, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\tools\python2\lib\site-packages\gyp-0.1-py2.7.egg\gyp\generator\ninja.py", line 2384, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\tools\python2\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\tools\python2\lib\multiprocessing\pool.py", line 558, in get
    raise self._value
AssertionError: 'C:/Users/mizchi/apps/electron/vendor/brightray/vendor/download/libchromiumcontent/src/content/app' can
not be absolute path (see crbug.com/462153).
None
Traceback (most recent call last):
  File ".\script\bootstrap.py", line 142, in <module>
    sys.exit(main())
  File ".\script\bootstrap.py", line 34, in main
    run_update()
  File ".\script\bootstrap.py", line 138, in run_update
    execute_stdout([sys.executable, update])
  File "C:\Users\mizchi\apps\electron\script\lib\util.py", line 152, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\tools\\python2\\python.exe', 'C:\\Users\\mizchi\\apps\\electron\\script\\u
pdate.py']' returned non-zero exit status 1
```

In my environment, v0.21.3 works but v0.25.3 failed

**Comment by zcbenz** [comment]
As mentioned in the output:

> (see crbug.com/462153)

It is a bug of upstream Chromium, I think you can use relative path to work around it.

**Comment by arthurakay** [comment]
"I think you can use relative path to work around it." 

Can you expand on that @zcbenz? I'm hitting this trying to build 0.26.0, where 0.25.2 seemed to work fine.

**Comment by tonny-zhang** [comment]
@mizchi did you resolved this problem?

that is my case:
```
d:\soft\Python27\python.exe f:\source\git_projects\electron_list\electron_201512
01\vendor\brightray\script\bootstrap --commit 17a4337f7948a45b5ea4b8f391df152ba8
db5979 --target_arch ia32 http://gh-contractor-zcbenz.s3.amazonaws.com/libchromi
umcontent
d:\soft\Python27\python.exe f:\source\git_projects\electron_list\electron_201512
01\script\update.py
Traceback (most recent call last):
  File "vendor\brightray\vendor\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "d:\soft\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", l
ine 545, in script_main
    return main(sys.argv[1:])
  File "d:\soft\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", l
ine 538, in main
    return gyp_main(args)
  File "d:\soft\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", l
ine 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "d:\soft\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\generator\ninja
.py", line 2386, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "d:\soft\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "d:\soft\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
AssertionError: 'f:/source/git_projects/electron_list/electron_20151201/vendor/b
rightray/vendor/download/libchromiumcontent/src/content/app' can not be absolute
 path (see crbug.com/462153).
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 210, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 51, in main
    run_update()
  File "script/bootstrap.py", line 206, in run_update
    execute_stdout([sys.executable, update])
  File "f:\source\git_projects\electron_list\electron_20151201\script\lib\util.p
y", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['d:\\soft\\Python27\\python.exe', 'f:\\
source\\git_projects\\electron_list\\electron_20151201\\script\\update.py']' ret
urned non-zero exit status 1
```

**Comment by tonny-zhang** [comment]
I resolve that change from `python 2.7.10`  to `python 2.7.3`
