### ISSUE TITLE
EBADF opening ASAR archive on Windows

### ISSUE THREAD

**Issue by paulcbetts** [atom/electron#1650]
Seems to be introduced by #1642:

```
Running: C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\slack.exe -e -r .
readFileSync: C:\Users\Paul\AppData\Local\Temp\slack-build\Slack\resources\atom.asar\browser\lib\init.js
fs.js:598
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EBADF: bad file descriptor, read
    at Error (native)
    at Object.fs.readSync (fs.js:598:19)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:415:10)
    at Object.Module._extensions..js (module.js:435:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Function.Module.runMain (module.js:459:10)
    at startup (node.js:131:18)
    at node.js:879:3
```

Doesn't seem to repro on OS X

**Comment by zcbenz** [comment]
It only happens in Release build, weird.
