### ISSUE TITLE
fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'

### ISSUE THREAD

**Issue by arthurakay** [atom/electron#1662]
I seem to be hitting this error consistently now, whether I'm building for windows 32 or 64bit per the build instructions.

```
[882/961] LINK_EMBED(DLL) node.dll
FAILED: c:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "c:\Python27\python.exe gy
p-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2
mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.manifest" obj\vendor\node\node.node.dll.generated.manifest
v8_base.lib(v8_base.api.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
Traceback (most recent call last):
  File "gyp-win-tool", line 316, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "c:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe
/nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1112
```

I gather it has something to do with a compilation issue... but I don't know what to do about it exactly.

I'm running Windows 8.1 64bit with Visual Studio 2013 (Update 4) -- executing the commands from a variety of terminals gives me the same error message.

I had the 32bit electron build working earlier, but then I must have done something to anger it because it no longer works. The only thing I can think of that changed was that I used `nvmw` to change the version of Node.js

**Comment by arthurakay** [comment]
I completely uninstalled Node, then reinstalled just the 32bit version (via Node installer). Still hitting the error... it's like something is forcing my environment to use a 64bit build, but I don't know what.

**Comment by arthurakay** [comment]
I just rebased by branch (previously off 0.25.2 tag) to the latest (0.26.0) and here is the most recent error / stack trace from running `build.py`:
```
[956/979] LINK_EMBED(DLL) node.dll
FAILED: c:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "c:\Py
thon27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.
lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.ma
nifest" obj\vendor\node\node.node.dll.generated.manifest
MSVCRT.lib(MSVCR120.dll) : error LNK2005: memmove already defined in LIBCMT.lib(memcpy.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: "public: bool __cdecl type_info::operator!=(class type_inf
o const &)const " (??9type_info@@QEBA_NAEBV0@@Z) already defined in LIBCMT.lib(typinfo.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: "public: bool __cdecl type_info::operator==(class type_inf
o const &)const " (??8type_info@@QEBA_NAEBV0@@Z) already defined in LIBCMT.lib(typinfo.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strncpy already defined in LIBCMT.lib(strncpy.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strchr already defined in LIBCMT.lib(strchr.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strncmp already defined in LIBCMT.lib(strncmp.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: sprintf already defined in LIBCMT.lib(sprintf.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strtod already defined in LIBCMT.lib(strtod.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: qsort already defined in LIBCMT.lib(qsort.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _vsnwprintf already defined in LIBCMT.lib(vsnwprnt.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: atoi already defined in LIBCMT.lib(atox.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: isdigit already defined in LIBCMT.lib(_ctype.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strrchr already defined in LIBCMT.lib(strrchr.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: free already defined in LIBCMT.lib(free.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: malloc already defined in LIBCMT.lib(malloc.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: realloc already defined in LIBCMT.lib(realloc.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strstr already defined in LIBCMT.lib(strstr.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: isspace already defined in LIBCMT.lib(_ctype.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strtoul already defined in LIBCMT.lib(strtol.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: atol already defined in LIBCMT.lib(atox.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: getenv already defined in LIBCMT.lib(getenv.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: __timezone already defined in LIBCMT.lib(timeset.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: __tzname already defined in LIBCMT.lib(timeset.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _tzset already defined in LIBCMT.lib(tzset.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strtol already defined in LIBCMT.lib(strtol.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: wcstombs already defined in LIBCMT.lib(wcstombs.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _aligned_free already defined in LIBCMT.lib(align.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _aligned_malloc already defined in LIBCMT.lib(align.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: exit already defined in LIBCMT.lib(crt0dat.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: __iob_func already defined in LIBCMT.lib(_file.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fclose already defined in LIBCMT.lib(fclose.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fwrite already defined in LIBCMT.lib(fwrite.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: abort already defined in LIBCMT.lib(abort.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fflush already defined in LIBCMT.lib(fflush.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: ungetc already defined in LIBCMT.lib(ungetc.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _lock_file already defined in LIBCMT.lib(_file.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _unlock_file already defined in LIBCMT.lib(_file.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: memcpy_s already defined in LIBCMT.lib(memcpy_s.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: printf already defined in LIBCMT.lib(printf.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fopen already defined in LIBCMT.lib(fopen.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fread already defined in LIBCMT.lib(fread.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fseek already defined in LIBCMT.lib(fseek.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: ftell already defined in LIBCMT.lib(ftell.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: feof already defined in LIBCMT.lib(feoferr.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: ferror already defined in LIBCMT.lib(feoferr.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fgets already defined in LIBCMT.lib(fgets.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: fprintf already defined in LIBCMT.lib(fprintf.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: sprintf_s already defined in LIBCMT.lib(sprintf.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: memchr already defined in LIBCMT.lib(memchr.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: strncpy_s already defined in LIBCMT.lib(strncpy_s.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: raise already defined in LIBCMT.lib(winsig.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _localtime64_s already defined in LIBCMT.lib(loctim64.obj)

MSVCRT.lib(MSVCR120.dll) : error LNK2005: fopen_s already defined in LIBCMT.lib(fopen.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: vfprintf already defined in LIBCMT.lib(vfprintf.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _vsnprintf_s already defined in LIBCMT.lib(vsnprnc.obj)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: _beginthreadex already defined in LIBCMT.lib(threadex.obj)

MSVCRT.lib(MSVCR120.dll) : error LNK2005: rand_s already defined in LIBCMT.lib(rand_s.obj)
MSVCRT.lib(ti_inst.obj) : error LNK2005: "private: __cdecl type_info::type_info(class type_info cons
t &)" (??0type_info@@AEAA@AEBV0@@Z) already defined in LIBCMT.lib(typinfo.obj)
MSVCRT.lib(ti_inst.obj) : error LNK2005: "private: class type_info & __cdecl type_info::operator=(cl
ass type_info const &)" (??4type_info@@AEAAAEAV0@AEBV0@@Z) already defined in LIBCMT.lib(typinfo.obj
)
MSVCRT.lib(MSVCR120.dll) : error LNK2005: "public: char const * __cdecl type_info::_name_internal_me
thod(struct __type_info_node *)const " (?_name_internal_method@type_info@@QEBAPEBDPEAU__type_info_no
de@@@Z) already defined in LIBCMT.lib(typinfo.obj)
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:libr
ary
node.dll : fatal error LNK1169: one or more multiply defined symbols found
Traceback (most recent call last):
  File "gyp-win-tool", line 316, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "c:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\Python27\python.exe gyp-win-tool link-wrapper environment
.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.
res' returned non-zero exit status 1169
ninja: build stopped: subcommand failed.
```

**Comment by arthurakay** [comment]
After deleting my local directory, re-cloning from GitHub, and clean/bootstrap/build things magically work again for a 32bit build.

I did notice that the default `--target_arch` is `ia32` so I'm wondering if something got cached when I originally set that to `x64` (or if x64 was simply the wrong target architecture for my WIndows 8.1 machine). In any case, I'll close this ticket as I am no longer bothered by the original problem.

**Comment by tonny-zhang** [comment]
https://github.com/atom/electron/issues/3654

mybe help you.
