### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden (libchromiumcontent) - bootstrapping on Windows

### ISSUE THREAD

**Issue by bstevens** [atom/electron#1687]
I'm having problems building Electron on Windows, specifically during the bootstrap phase. The error details are shown below:

```
runas@2.0.0 node_modules\runas
+-- nan@1.6.1
npm verb exit [ 0, true ]
npm info ok
C:\Python27\python.exe E:\eniware-prototype\dist\electron\vendor\brightray\scrip
t\bootstrap --commit 90a5b9c3792645067ad9517e60cf5eb99730e0f9 --target_arch ia32
 http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent
Downloading libchromiumcontent.zip...
http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent/win/ia32/90a5b9c
3792645067ad9517e60cf5eb99730e0f9/libchromiumcontent.zip
Traceback (most recent call last):
  File "E:\eniware-prototype\dist\electron\vendor\brightray\vendor\libchromiumco
ntent\script\download", line 151, in <module>
    sys.exit(main())
  File "E:\eniware-prototype\dist\electron\vendor\brightray\vendor\libchromiumco
ntent\script\download", line 41, in main
    args.force)
  File "E:\eniware-prototype\dist\electron\vendor\brightray\vendor\libchromiumco
ntent\script\download", line 97, in download_if_needed
    download(destination, base_url, commit, filename)
  File "E:\eniware-prototype\dist\electron\vendor\brightray\vendor\libchromiumco
ntent\script\download", line 107, in download
    download_and_extract(destination, url)
  File "E:\eniware-prototype\dist\electron\vendor\brightray\vendor\libchromiumco
ntent\script\download", line 120, in download_and_extract
    with contextlib.closing(urllib2.urlopen(url)) as u:
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "E:\eniware-prototype\dist\electron\vendor\brightray\script\bootstrap", l
ine 63, in <module>
    sys.exit(main())
  File "E:\eniware-prototype\dist\electron\vendor\brightray\script\bootstrap", l
ine 19, in main
    download_libchromiumcontent(args.dev, args.commit, args.target_arch, args.ur
l)
  File "E:\eniware-prototype\dist\electron\vendor\brightray\script\bootstrap", l
ine 51, in download_libchromiumcontent
    subprocess.check_call([sys.executable, download, '-s'] + args)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'E:\\eniwar
e-prototype\\dist\\electron\\vendor\\brightray\\vendor\\libchromiumcontent\\scri
pt\\download', '-s', '-f', '-c', '90a5b9c3792645067ad9517e60cf5eb99730e0f9', '--
target_arch', 'ia32', 'http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumc
ontent', 'E:\\eniware-prototype\\dist\\electron\\vendor\\brightray\\vendor\\down
load\\libchromiumcontent']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 142, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 30, in main
    bootstrap_brightray(args.dev, args.url, args.target_arch)
  File "script\bootstrap.py", line 82, in bootstrap_brightray
    execute_stdout([sys.executable, bootstrap] + args)
  File "E:\eniware-prototype\dist\electron\script\lib\util.py", line 152, in exe
cute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'E:\\eniwar
e-prototype\\dist\\electron\\vendor\\brightray\\script\\bootstrap', '--commit',
'90a5b9c3792645067ad9517e60cf5eb99730e0f9', '--target_arch', 'ia32', 'http://gh-
contractor-zcbenz.s3.amazonaws.com/libchromiumcontent']' returned non-zero exit
status 1
```

I'm not an expert at diagnosing python error messages so I'm posting here in the hope that someone can help. Does the HTTP Error 403: Forbidden error indicates some sort of read/write issue with the remote url? How can I resolve this and move on?

Setup:
* Windows 7 32bit
* VS2013 Community Edition
* Node v.0.10.38
* Using Command Prompt as adminstrator

**Comment by maxkorp** [comment]
+1, only an issue since switching from 0.24 to 0.26

**Comment by maxkorp** [comment]
Yup, error downloading libchromium content. This seems to be the root of the issue

![Permission error](http://i.imgur.com/0yV1eaf.png)

**Comment by paulcbetts** [comment]
^^ what @maxkorp said, pass `--target_arch x64` into bootstrap to work around this for the moment

**Comment by zcbenz** [comment]
Sorry I forgot to upload 32bit build of libchromiumcontent, it should work now.

**Comment by Ldes** [comment]
Hi. Same trouble.
- Windows 7 32bit
- MVS2015 Community Edition
- Node v6.3.1-x86
- Command Prompt as adminstrator

`python script\bootstrap.py -v --target_arch=ia32`

>C:\Python27\python.exe C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap --commit 086d162df096
2c12d2db5a9fbe488aa52ad9a327 --target_arch ai32 https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent
Downloading libchromiumcontent.zip...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/win/ai32/086d162df0962c12d2db5a9fbe488aa52ad9a327/lib
chromiumcontent.zip
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 180,
 in <module>
    sys.exit(main())
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 61,
in main
    args.force)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 126,
 in download_if_needed
    download(destination, base_url, commit, filename)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 136,
 in download
    download_and_extract(destination, url)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 149,
 in download_and_extract
    with contextlib.closing(urllib2.urlopen(url)) as u:
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 397, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap", line 98, in <module>
    sys.exit(main())
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap", line 31, in main
    args.libcc_static_library_path)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap", line 86, in setup_libchromiumconte
nt
    subprocess.check_call([sys.executable, download, '-s'] + args)
  File "C:\Python27\lib\subprocess.py", line 504, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\IEUser\\Desktop\\electron\\electron\\ve
ndor\\brightray\\vendor\\libchromiumcontent\\script\\download', '-s', '-f', '-c', '086d162df0962c12d2db5a9fbe488aa52ad9a
327', '--target_arch', 'ai32', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', 'C:\\Users\\IEUser\
\Desktop\\electron\\electron\\vendor\\brightray\\vendor\\download\\libchromiumcontent']' returned non-zero exit status 1

> None
Traceback (most recent call last):
  File ".\script\bootstrap.py", line 265, in <module>
    sys.exit(main())
  File ".\script\bootstrap.py", line 61, in main
    libcc_static_library_path)
  File ".\script\bootstrap.py", line 155, in bootstrap_brightray
    execute_stdout([sys.executable, bootstrap] + args)
  File "C:\Users\IEUser\Desktop\electron\electron\script\lib\util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\IEUser\\Desktop\\electron\\electron\\ve
ndor\\brightray\\script\\bootstrap', '--commit', '086d162df0962c12d2db5a9fbe488aa52ad9a327', '--target_arch', 'ai32', 'h
ttps://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent']' returned non-zero exit status 1
