### ISSUE TITLE
Error raise up when call window maximize after window reload

### ISSUE THREAD

**Issue by eric-nyq** [atom/electron#1744]
sample code:
-------------------
```
require('remote').getCurrentWindow().reload();
require('remote').getCurrentWindow().maximize();
```

environment:
--------------------
Window 7 (64-bit)
Electrom (32-bit) v0.26.0

error detail:
-------------------
```
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Calling a callback of released renderer view
    at BrowserWindow.ret (D:\{fakepath}\Atom\resources\atom.asar\browser\lib\rpc-server.js:90:21)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (D:\{fakepath}\Atom\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (D:\{fakepath}\Atom\resources\atom.asar\browser\lib\rpc-server.js:212:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:179:7)
    at EventEmitter.<anonymous> (D:\{fakepath}\Atom\resources\atom.asar\browser\api\lib\web-contents.js:96:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

screenshot:
---------------------
![error](https://cloud.githubusercontent.com/assets/12454699/7752478/53128738-0012-11e5-8b6b-ed433cdf6be3.png)

**Comment by eric-nyq** [comment]
---------------------------
A JavaScript error occured in the browser process
---------------------------
Uncaught Exception:
Error: Calling a callback of released renderer view
    at BrowserWindow.ret (D:\AVIDMCLIENT\工具文档\Atom\resources\atom.asar\browser\lib\rpc-server.js:90:21)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (D:\AVIDMCLIENT\工具文档\Atom\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (D:\AVIDMCLIENT\工具文档\Atom\resources\atom.asar\browser\lib\rpc-server.js:212:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:179:7)
    at EventEmitter.<anonymous> (D:\AVIDMCLIENT\工具文档\Atom\resources\atom.asar\browser\api\lib\web-contents.js:96:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
---------------------------
确定   
---------------------------

**Comment by zcbenz** [comment]
You must have registered a callback to the BrowserWindow object in web page, see more about it at https://github.com/atom/electron/blob/master/docs/api/remote.md#passing-callbacks-to-the-main-process.
