### ISSUE TITLE
0.27.1: weird stacktrace showing up after using devtools

### ISSUE THREAD

**Issue by bpasero** [atom/electron#1810]
Found this in my logs, not sure how to repro. I am on Mac:

[3433:0529/070909:ERROR:CONSOLE(1364)] "TypeError: WebInspector.ObjectPropertiesSection.formatObjectAsFunction is not a function TypeError: WebInspector.ObjectPropertiesSection.formatObjectAsFunction is not a function
    at Object.didQueryObject (chrome-devtools://devtools/inspector.js:8838:38)
    at Object.showObjectPopover (chrome-devtools://devtools/sources_module.js:642:34)
    at didEvaluateOnCallFrame (chrome-devtools://devtools/inspector.js:5110:1)
    at Object.InspectorBackendClass.AgentPrototype.dispatchResponse (chrome-devtools://devtools/inspector.js:3800:10)
    at Object.InspectorBackendClass.Connection.dispatch (chrome-devtools://devtools/inspector.js:3718:60)
    at Object.InspectorBackendClass.MainConnection._dispatchMessage (chrome-devtools://devtools/inspector.js:3743:7)
    at Object.WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/inspector.js:744:185)
    at innerDispatch (chrome-devtools://devtools/inspector.js:1364:58)
    at Object.InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/inspector.js:1363:1)
    at dispatch (chrome-devtools://devtools/devtools.js:1421:59)", source: chrome-devtools://devtools/inspector.js (1364)

**Comment by zcbenz** [comment]
This should have been fixed in 0.28.
