### ISSUE TITLE
bootstrap.py recently started failing with permission error

### ISSUE THREAD

**Issue by apm** [atom/electron#1858]
Last week on master, this did not happen.  Ubuntu 14.04 LTS

/usr/bin/python /home/adam/src/electron/script/update.py
Traceback (most recent call last):
  File "vendor/brightray/vendor/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "vendor/brightray/vendor/gyp/pylib/gyp/__init__.py", line 532, in script_main
    return main(sys.argv[1:])
  File "vendor/brightray/vendor/gyp/pylib/gyp/__init__.py", line 525, in main
    return gyp_main(args)
  File "vendor/brightray/vendor/gyp/pylib/gyp/__init__.py", line 501, in gyp_main
    params, options.check, options.circular_check)
  File "vendor/brightray/vendor/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "vendor/brightray/vendor/gyp/pylib/gyp/input.py", line 2730, in Load
    check, generator_input_info)
  File "vendor/brightray/vendor/gyp/pylib/gyp/input.py", line 596, in LoadTargetBuildFilesParallel
    parallel_state.pool = multiprocessing.Pool(multiprocessing.cpu_count())
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 138, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 234, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 142, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 34, in main
    run_update()
  File "./script/bootstrap.py", line 138, in run_update
    execute_stdout([sys.executable, update])
  File "/home/adam/src/electron/script/lib/util.py", line 152, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/adam/src/electron/script/update.py']' returned non-zero exit status 1

**Comment by hokein** [comment]
Looks like you don't have permission. here might be the answer for you: http://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied

**Comment by apm** [comment]
Aha, thanks. I rebooted that machine for the first time in a while, and permissions must have reverted to the broken state.
