### ISSUE TITLE
Calling dialog.showOpenDialog() throws error processing argument 2

### ISSUE THREAD

**Issue by astoilkov** [atom/electron#1912]
I have tried everything. Adding all needed arguments. Removing all arguments. Supplying only some of the arguments. Passing different options. Always the same error. Tried under Windows and Mac. Running the code from the renderer process and requiring dialog using `remote.require('dialog');`. The exact same approach works perfectly for `showSaveDialog`.

```javascript
// I have tried supplying the currently focused window, removing the function, changing the options
dialog.showOpenDialog({
  title: 'Open a file',
  properties: ['openFile'],
  filters: [
    { name: 'Markdown', extensions: ['md'] },
    { name: 'Text', extensions: 'txt' }
  ]
}, function () {});
```

The error is always:
```
[8548:0609/210137:INFO:CONSOLE(77)] "Uncaught Error: Error processing argument 2.
TypeError: Error processing argument 2.
    at TypeError (native)
    at Object.module.exports.showOpenDialog (C:\Users\anton_000\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\
resources\atom.asar\browser\api\lib\dialog.js:80:22)
    at callFunction (C:\Users\anton_000\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\atom.asar\brow
ser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\anton_000\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\at
om.asar\browser\lib\rpc-server.js:212:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:179:7)
    at EventEmitter.<anonymous> (C:\Users\anton_000\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\at
om.asar\browser\api\lib\web-contents.js:96:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)", source: C:\Users\anton_000\AppData\Roaming\npm\node_modules\electron-prebui
lt\dist\resources\atom.asar\renderer\api\lib\remote.js (77)
```

**Comment by deepak1556** [comment]
filter#extensions is an array of file types. should probably handle the scenarios where it isnt.

```
  filters: [
    { name: 'Markdown', extensions: ['md'] },
    { name: 'Text', extensions: ['txt'] }
  ]
```

**Comment by astoilkov** [comment]
Grrr. I hate this kind of mistakes. Thanks a lot. Have a great day.
