### ISSUE TITLE
Menu documentation is out of date

### ISSUE THREAD

**Issue by alexwarren** [atom/electron#1915]
The [menu documentation](https://github.com/atom/electron/blob/master/docs/api/menu.md) gives an example of creating the application menu with the simple template API, with the comment that the code belongs in `main.js`.

However, the code doesn't work there - it gives this error:

```
Uncaught Exception:
ReferenceError: Menu is not defined
    at EventEmitter.<anonymous> (/Users/alexwarren/Documents/Projects/squiffy-editor/main.js:171:14)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
```

Adding these lines from the `index.html` example doesn't help either:

    var remote = require('remote');
    var Menu = remote.require('menu');

... because then you get:

```
Error: Cannot find module 'remote'
```

It *does* work if you place it in `index.html`... in as much as the menus are created. **But** then the "Reload" and "Toggle DevTools" menus don't work, because they require a reference to `BrowserWindow`.

**Comment by alexwarren** [comment]
If the code is in `index.html`, the "Reload" and "Toggle DevTools" menus can be fixed using

    var remote = require('remote');

and then replace `BrowserWindow.getFocusedWindow()` with `remote.getCurrentWindow()`
