### ISSUE TITLE
How set custom handler for http/https protocols?

### ISSUE THREAD

**Issue by DsXack** [atom/electron#2010]
`protocol.registerProtocol('http', handler) ` throws
```
Uncaught Exception:
Error: The scheme is already registered
    at Error (native)
    at EventEmitter.<anonymous> (/Users/dsxack/workspace/src/unpublished/browser/index.js:16:14)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```
or

`protocol.interceptProtocol('http', handler) ` throws
```
Uncaught Exception:
Error: Scheme does not exist.
    at Error (native)
    at EventEmitter.<anonymous> (/Users/dsxack/workspace/src/unpublished/browser/index.js:16:14)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

#1970 will help me?

**Comment by zcbenz** [comment]
You need to use latest version.

**Comment by DsXack** [comment]
@zcbenz, i use latest version. I have same problems

**Comment by zcbenz** [comment]
Can you share a demo app?
