### ISSUE TITLE
electron-prebuilt 0.27.2 using git-utils 3.0.1 module fails on Windows 8.1 x64

### ISSUE THREAD

**Issue by gisenberg** [atom/electron#2061]
Hey folks,

I've put together an Electron app using git-utils that works great on OSX, but fails to run on my Windows box with the following error:

```
C:\...\app\node_modules\git-utils\build\Release\git.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:134:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:134:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Module.require (module.js:353:17)
    at require (module.js:372:17)
    at Object.<anonymous> (C:\...\app\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> (C:\...\app\node_modules\git-utils\lib\git.js:371:4)
    at Module._compile (module.js:418:26)", source: file:///C:/.../app/generated/src/index.js (15)
```

Being familiar with this error from getting the app running on OSX, I did all the usual stuff: clear and reinstall packages through APM, clear node_modules, toast Roaming node_modules and cache, tried x86 and x64 versions of nodejs 0.10.35, and so on, with no luck.

Here's what apm and node have to say about versions on Windows:
```
C:\...\app>apm --version
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.8
git 1.9.4.msysgit.1
visual studio 2013
C:\...\app>node --version
v0.10.35
```

This is about in-line with the versions I'm using in OSX, where things appear to run fine:
```
gisenberg@gabe-mbp15:~/Development/app (master) $ apm --version
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.6
git 2.3.5
gisenberg@gabe-mbp15:~/Development/app (master) $ node --version
v0.10.39

```

And here's my package.json for reference:

```
{
  "name": "sample",
  "version": "0.1.0",
  "description": "description",
  "main": "app/generated/src/browser/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "gisenberg",
  "license": "ISC",
  "devDependencies": {
    "electron-prebuilt": "0.27.2",
  },
  "dependencies": {
    "difflib": "0.2.4",
    "git-utils": "3.0.1",
    "request": "2.58.0"
  }
}
```

What did I miss?

Thanks!

**Comment by zcbenz** [comment]
You need to follow Electron's documents to install native modules:
https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

There is also a module to simplify the progress:
https://github.com/paulcbetts/electron-rebuild

**Comment by gisenberg** [comment]
I went through the electron-rebuild process, but still encounter the same issue. Is that approach going to work with electron-prebuilt? Console output below:

```
C:\...\app>npm install --save-dev electron-rebuild
npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz
/
> nslog@2.0.0 install C:\...\app\node_modules\electron-rebuild\node_modules\nslog
> node-gyp rebuild


C:\...\app\node_modules\electron-rebuild\node_modules\nslog>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gy
p-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
     Creating library C:\...\app\node_modules\electron-rebuild\node_modules\nslog\build\Release\nslog.lib and object C:\Use
  rs\Gabriel\Development\codiff\spikes\app\node_modules\electron-rebuild\node_modules\nslog\build\Release\nslog.exp
  Generating code
  Finished generating code
  nslog.vcxproj -> C:\...\app\node_modules\electron-rebuild\node_modules\nslog\build\Release\\nslog.node
electron-rebuild@0.2.2 node_modules\electron-rebuild
├── ncp@2.0.0
├── promise@7.0.3 (asap@2.0.3)
├── yargs@3.13.0 (decamelize@1.0.0, window-size@0.1.1, camelcase@1.1.0, cliui@2.1.0)
├── rimraf@2.4.0 (glob@4.5.3)
├── lodash@3.9.3
├── babel-core@5.6.14 (slash@1.0.0, babel-plugin-remove-console@1.0.1, babel-plugin-eval@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-js
cript@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, babel-plugin-remove-debu
gger@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-constant-folding@1.0.1, babel-plugin-react-display-name@1.0.3, path-exists@1.0.0, to-fast-p
roperties@1.0.1, shebang-regex@1.0.0, path-is-absolute@1.0.0, trim-right@1.0.0, babel-plugin-proto-to-assign@1.0.3, fs-readdir-recursive@0.1.2, babel-plugin-dea
d-code-elimination@1.0.2, strip-json-comments@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, estraverse@4.1.0, esutils@2.0.2, convert-source-m
ap@1.1.1, js-tokens@1.0.1, line-numbers@0.2.0, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, debug@2.2.0, ast-types@0.7.6, detect-indent@3.0
.1, repeating@1.1.3, minimatch@2.0.8, chalk@1.0.0, output-file-sync@1.1.1, resolve@1.1.6, is-integer@1.0.4, babel-eslint@3.1.19, source-map@0.4.2, acorn-jsx@1.0
.3, source-map-support@0.2.10, regexpu@1.2.0, regenerator@0.8.31, core-js@0.9.18)
├── npm@2.12.0
└── nslog@2.0.0 (nan@1.6.1)

C:\...\app>node_modules\.bin\electron-rebuild

C:\...\app>run

C:\...\app>node_modules/.bin/electron .
[6616:0626/094057:INFO:renderer_main.cc(200)] Renderer process started
[3648:0626/094057:INFO:CONSOLE(15)] "Error: The specified module could not be found.
C:\...\app\node_modules\git-utils\build\Release\git.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:134:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:134:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Module.require (module.js:353:17)
    at require (module.js:372:17)
    at Object.<anonymous> (C:\...\app\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> (C:\...\app\node_modules\git-utils\lib\git.js:371:4)
    at Module._compile (module.js:418:26)", source: file:///C:/.../app/app/generated/src/index.js (15)
```

**Comment by zcbenz** [comment]
> npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz

There is some networking error according to the log, it should be related to Atom 1 release a few days ago. You might try running `npm install --save-dev electron-rebuild` again.

**Comment by gisenberg** [comment]
Thanks for the followup. I tried again and I'm still seeing the same issue.

I've put together a minimal repro at this repository: https://github.com/gisenberg/electron-2061

`repro.ps1` contains the commands I'm running:
```
apm install
npm install electron-rebuild --save-dev
.\node_modules\.bin\electron-rebuild .
.\node_modules\.bin\electron .
```

Here's the output of running repro.ps1 at the repository:
```
PS C:\Users\Gabriel\Development\test> .\repro.ps1
Installing modules done
npm WARN package.json electron-test@0.1.0 No repository field.
npm WARN package.json electron-test@0.1.0 No README data
-


> nslog@2.0.0 install C:\Users\Gabriel\Development\test\node_modules\electron-rebuild\node_modules\nslog
> node-gyp rebuild


C:\Users\Gabriel\Development\test\node_modules\electron-rebuild\node_modules\nslog>node "C:\Program Files (x86)\nodejs\n
ode_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
     Creating library C:\Users\Gabriel\Development\test\node_modules\electron-rebuild\node_modules\nslog\build\Release\
  nslog.lib and object C:\Users\Gabriel\Development\test\node_modules\electron-rebuild\node_modules\nslog\build\Release
  \nslog.exp
  Generating code
  Finished generating code
  nslog.vcxproj -> C:\Users\Gabriel\Development\test\node_modules\electron-rebuild\node_modules\nslog\build\Release\\ns
  log.node
electron-rebuild@0.2.2 node_modules\electron-rebuild
├── ncp@2.0.0
├── promise@7.0.3 (asap@2.0.3)
├── yargs@3.14.0 (window-size@0.1.1, decamelize@1.0.0, camelcase@1.1.0, cliui@2.1.0)
├── rimraf@2.4.0 (glob@4.5.3)
├── lodash@3.9.3
├── nslog@2.0.0 (nan@1.6.1)
├── babel-core@5.6.15 (slash@1.0.0, babel-plugin-eval@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-re
move-debugger@1.0.1, babel-plugin-constant-folding@1.0.1, babel-plugin-member-expression-literals@1.0.1, babel-plugin-re
move-console@1.0.1, babel-plugin-jscript@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-property-l
iterals@1.0.1, babel-plugin-react-display-name@1.0.3, babel-plugin-undefined-to-void@1.1.6, babel-plugin-dead-code-elimi
nation@1.0.2, babel-plugin-proto-to-assign@1.0.3, fs-readdir-recursive@0.1.2, to-fast-properties@1.0.1, path-is-absolute
@1.0.0, shebang-regex@1.0.0, trim-right@1.0.0, path-exists@1.0.0, strip-json-comments@1.0.2, babel-plugin-runtime@1.0.7,
 private@0.1.6, globals@6.4.1, estraverse@4.1.0, esutils@2.0.2, convert-source-map@1.1.1, line-numbers@0.2.0, home-or-tm
p@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, js-tokens@1.0.1, debug@2.2.0, ast-types@0.7.8, detect-indent@3.0
.1, repeating@1.1.3, chalk@1.0.0, minimatch@2.0.8, output-file-sync@1.1.1, resolve@1.1.6, is-integer@1.0.4, source-map-s
upport@0.2.10, source-map@0.4.2, acorn-jsx@1.0.3, regexpu@1.2.0, regenerator@0.8.31, core-js@0.9.18)
└── npm@2.12.0
[2932:0629/105536:INFO:CONSOLE(0)] [Error: The specified module could not be found.
C:\Users\Gabriel\Development\test\node_modules\git-utils\build\Release\git.node]
[2932:0629/105536:INFO:CONSOLE(0)] Error: The specified module could not be found.
C:\Users\Gabriel\Development\test\node_modules\git-utils\build\Release\git.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:134:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:134:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Module.require (module.js:353:17)
    at require (module.js:372:17)
    at Object.<anonymous> (C:\Users\Gabriel\Development\test\node_modules\git-utils\lib\git.js:8:16)
    at Object.<anonymous> (C:\Users\Gabriel\Development\test\node_modules\git-utils\lib\git.js:371:4)
    at Module._compile (module.js:418:26)
```

**Comment by zcbenz** [comment]
@gisenberg You should remove `node_modules` and try again, `npm` does not work well with partial-installed modules.

**Comment by gisenberg** [comment]
I've removed node_modules and all relevant caches, but still see the same issue.

**Comment by zcbenz** [comment]
You don't need to run `apm install`.

**Comment by gisenberg** [comment]
Removed `apm install`, replaced with `npm install`, still seeing the same behavior.

**Comment by damieng** [comment]
Am now also seeing this.
