### ISSUE TITLE
bootstrap failed on Windows if checkout by tag v0.28.3

### ISSUE THREAD

**Issue by aspoon** [atom/electron#2086]
I am trying to checkout and build electron by tag `v0.28.3` on Windows 8.1 with Python 2.7.10, Git 1.9.5, and VS2013 Community installed.  The whole process works fine if I am checking out `HEAD`.

```
C:\...> git clone -b v0.28.3 https://github.com/atom/electron.git

    ...

C:\...> cd electron
C:\...\electron> script\bootstrap.py -v --target_arch=x64

    ...

Submodule path 'vendor/native_mate': checked out 'ad207eeabb0185f74c017e70ca3411
d522627ff0'
Cloning into 'vendor/node'...
remote: Counting objects: 161023, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 161023 (delta 360), reused 324 (delta 324), pack-reused 160622
Receiving objects: 100% (161023/161023), 104.39 MiB | 7.80 MiB/s, done.
Resolving deltas: 100% (125984/125984), done.
Checking connectivity... done.
fatal: reference is not a tree: ab1b3ba0b0076d7aa72e80caf8045fb6f7a68be0
Unable to checkout 'ab1b3ba0b0076d7aa72e80caf8045fb6f7a68be0' in submodule path
'vendor/node'
None
Traceback (most recent call last):
  File "C:\...\electron\script\bootstrap.py", line 142,
 in <module>
    sys.exit(main())
  File "C:\...\electron\script\bootstrap.py", line 28,
in main
    update_submodules()
  File "C:\...\electron\script\bootstrap.py", line 70,
in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\...\electron\script\lib\util.py", line 152,
in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init',
 '--recursive']' returned non-zero exit status 1
C:\...\electron>
```

Some guidance would be appreciated if this is not the proper way of building a specific tagged version.

Thanks!

**Comment by candidosales** [comment]
I'm the same error, can anyone help?

**Comment by michaelkruglos** [comment]
Same problem on Linux. There's some bad reference to commit in submodule atom/node which doesn't exist on github. Also latest tag in atom/node is v0.27.3. Please update atom/node repo on github to correspond to submodule references in electron v0.28.3, otherwise we can't build it.

**Comment by zcbenz** [comment]
Sorry I forgot to push a tag to node repo, it should work now.
