### ISSUE TITLE
node-spellchecker doesn't work in 0.29.2

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#2151]
Have given all the ways of compiling the native addon modules.

http://atom.github.io/node-spellchecker
https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md
Node details :
```
Process.versions : 
http_parser: '2.5.0',
  node: '2.3.3',
  v8: '4.2.77.20',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '44',
  openssl: '1.0.2c' }

npm-version : 2.11.3
node --version : v2.3.3
```
When i require("spellchecker") in terminal it works fine, when i require in Electron the following error is
thrown.  Can somebody let us know, is the spellchecker is working in 0.29.2. That is a major dependency which needed for our app.

```

Uncaught Error: Module version mismatch. Expected 44, got 43.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/kamesharumugam/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)module.(anonymous function) @ ATOM_SHELL_ASAR.js:137module.(anonymous function) @ ATOM_SHELL_ASAR.js:137Module.load @ module.js:353Module._load @ module.js:308Module.require @ module.js:363require @ module.js:382(anonymous function) @ /Users/kamesharumugam/node_modules/spellchecker/lib/spellchecker.js:2Module._compile @ module.js:428Module._extensions..js @ module.js:446Module.load @ module.js:353Module._load @ module.js:308Module.require @ module.js:363require @ module.js:382(anonymous function) @ VM78:2InjectedScript._evaluateOn @ VM77:895InjectedScript._evaluateAndWrap @ VM77:828InjectedScript.evaluate @ VM77:694
require('spellchecker')
ATOM_SHELL_ASAR.js:137 Uncaught Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/kamesharumugam/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)

````

**Comment by zcbenz** [comment]
The module has been built for the wrong version of electron, please remove `node_modules` and install the module with the "npm way" in the documents:

```
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.29.2
export npm_config_arch=x64
HOME=~/.electron-gyp npm install spellchecker
```

**Comment by kamesh-a** [comment]
yes correct, We tried npm way as well, even once again i tried right now, cleaned all the cache. It didn't work. Let me know your thought on this.

**Comment by zcbenz** [comment]
You can run npm with `--verbose` and paste the log here.

**Comment by kamesh-a** [comment]
Able to figure out the issue, compilation was proper but there was global module of spellchecker installed when i was trying 0.26.x version when i started working with atom. That global module was referred instead of the recompiled local one.

Hope it might help someone, if they fall into similar issue while referencing modules. 

Thanks

**Comment by kamesh-a** [comment]
I don't want to create another issue card, Error:  "spellchecker" is working in OS-X

A dynamic link library (DLL) initialization routine failed. on Windows #18

**Comment by kamesh-a** [comment]
@zcbenz Can you please reopen this issue or you want me to create a separate card for this.

Thanks.

**Comment by zcbenz** [comment]
@kamesh-a Having an issue opened at node-spellchecker is enough.
