### ISSUE TITLE
Error using NodObjC

### ISSUE THREAD

**Issue by mjackson** [atom/electron#2217]
I'm trying to use NodObjC in my Electron app, but I can't seem to figure out how to `require('nodobjc')` without throwing an error. The stack trace is:

```
Uncaught Exception:
Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at bindings (/Users/michael/Projects/unsplash-desktop-osx/node_modules/nodobjc/node_modules/ref/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/michael/Projects/unsplash-desktop-osx/node_modules/nodobjc/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:428:26)
```

It looks like this may be related to #712, but I've tried running `electron-rebuild` from inside my project directory and even inside `./node_modules/nodobjc` with no success. I'm not sure if `electron-rebuild` is supposed to give me some kind of output, but it doesn't.

Any idea what I need to do here? Thanks!

**Comment by mjackson** [comment]
Also possibly related is #1549

**Comment by paulcbetts** [comment]
It looks like electron-rebuild might be incorrectly detecting that node modules are already built - try running with `-f`

**Comment by mjackson** [comment]
Ah, that did it. Thanks @paulcbetts! :dancer:

**Comment by niftylettuce** [comment]
@mjackson How was it related to #712? @paulcbetts 

Can I get some help on that issue btw?

**Comment by paulcbetts** [comment]
@niftylettuce #712 isn't an actual single issue, it's just a generic "rebuild didn't work" and there are 120312320x reasons why this could be the case

**Comment by liushaohua** [comment]
@mjackson `"start": "electron main.js -f"`  it like this？
