### ISSUE TITLE
crash when intercepting http and returning undefined

### ISSUE THREAD

**Issue by zsalzbank** [atom/electron#2286]
When I intercept the HTTP scheme, but do nothing (my `handler` returns `undefined`), electron crashes.  Here is the [sample app](https://gist.github.com/zsalzbank/505d3bda65318bae9740) that illustrates the crash.  When I comment out the javascript block of `index.htm`, the app does not crash, so it has something to do with how that file is loaded.

I build electron locally and ran the application, and I get a segfault in `libchromiumcontent` I think:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1835700 (LWP 15919)]
net::URLRequestJob::ReadFilteredData (this=0xebf18e5500, bytes_read=0x7fffe1834134) at ../../net/url_request/url_request_job.cc:709
709	../../net/url_request/url_request_job.cc: No such file or directory.
(gdb) bt
#0  net::URLRequestJob::ReadFilteredData (this=0xebf18e5500, bytes_read=0x7fffe1834134) at ../../net/url_request/url_request_job.cc:709
#1  0x0000000000d35e32 in net::URLRequestJob::NotifyReadComplete (this=0xebf18e5500, bytes_read=2463) at ../../net/url_request/url_request_job.cc:552
#2  0x0000000000d324b9 in net::URLRequestHttpJob::OnReadCompleted (this=<optimized out>, result=0) at ../../net/url_request/url_request_http_job.cc:958
#3  0x0000000000bc41dc in Run (this=0xebf1e90b80, args=@0x2cfe51a00000000: <error reading variable>) at ../../base/callback.h:396
#4  tracked_objects::ScopedTracker::ExecuteAndTrackCallback<int>(tracked_objects::Location const&, base::Callback<void (int)> const&, int) (location=..., callback=..., p1=0)
    at ../../base/profiler/scoped_tracker.h:66
#5  0x0000000000c36086 in Run (this=0xebf1e90b40, args=<optimized out>) at ../../base/callback.h:396
#6  net::HttpCache::Transaction::DoCallback (this=<optimized out>, rv=<optimized out>) at ../../net/http/http_cache_transaction.cc:733
#7  0x0000000000c34bee in HandleResult (this=0xebf1da4a80, rv=<optimized out>) at ../../net/http/http_cache_transaction.cc:739
#8  net::HttpCache::Transaction::DoLoop (this=0xebf1da4a80, result=<optimized out>) at ../../net/http/http_cache_transaction.cc:1034
#9  0x0000000000c343a2 in net::HttpCache::Transaction::OnIOComplete (this=0xebf1dc0700, result=-511491788) at ../../net/http/http_cache_transaction.cc:3255
#10 0x0000000000bc41dc in Run (this=0xebf1e90b30, args=@0x2cfe51a00000000: <error reading variable>) at ../../base/callback.h:396
#11 tracked_objects::ScopedTracker::ExecuteAndTrackCallback<int>(tracked_objects::Location const&, base::Callback<void (int)> const&, int) (location=..., callback=..., p1=0)
    at ../../base/profiler/scoped_tracker.h:66
#12 0x0000000000bc4073 in Run (this=0xebf1e90af0, args=@0x2cfe51a00000000: <error reading variable>) at ../../base/callback.h:396
#13 disk_cache::InFlightBackendIO::OnOperationComplete (this=<optimized out>, operation=0xebf1e98b60, cancel=<optimized out>) at ../../net/disk_cache/blockfile/in_flight_backend_io.cc:578
#14 0x0000000000bc44a5 in disk_cache::InFlightIO::InvokeCallback (this=0xebf1da4708, operation=0xebf1e98b60, cancel_task=false) at ../../net/disk_cache/blockfile/in_flight_io.cc:109
#15 0x000000000255c25a in Run (this=<optimized out>) at ../../base/callback.h:396
#16 base::debug::TaskAnnotator::RunTask (this=<optimized out>, queue_function=<optimized out>, run_function=<optimized out>, pending_task=...) at ../../base/debug/task_annotator.cc:63
#17 0x0000000002575ad2 in base::MessageLoop::RunTask (this=0xebf1941d80, pending_task=...) at ../../base/message_loop/message_loop.cc:444
#18 0x0000000002575c69 in base::MessageLoop::DeferOrRunPendingTask (this=0xebf1941d80, pending_task=...) at ../../base/message_loop/message_loop.cc:454
#19 0x0000000002575f9b in base::MessageLoop::DoWork (this=0xebf1941d80) at ../../base/message_loop/message_loop.cc:566
#20 0x00000000025553a9 in base::MessagePumpLibevent::Run (this=0xebf1936cc0, delegate=0xebf1941d80) at ../../base/message_loop/message_pump_libevent.cc:232
#21 0x0000000002587790 in base::RunLoop::Run (this=0x7fffe1834848) at ../../base/run_loop.cc:55
#22 0x000000000257553a in base::MessageLoop::Run (this=<optimized out>) at ../../base/message_loop/message_loop.cc:303
#23 0x00000000015de436 in content::BrowserThreadImpl::IOThreadRun (this=0xebf1dc0700, message_loop=0x7fffe1834134) at ../../content/browser/browser_thread_impl.cc:218
#24 0x00000000015de5ae in content::BrowserThreadImpl::Run (this=0xebf17422d0, message_loop=0xebf1941d80) at ../../content/browser/browser_thread_impl.cc:253
#25 0x00000000025a64c4 in base::Thread::ThreadMain (this=0xebf17422d0) at ../../base/threading/thread.cc:239
#26 0x00000000025a2bbc in base::(anonymous namespace)::ThreadFunc (params=<optimized out>) at ../../base/threading/platform_thread_posix.cc:77
#27 0x00007ffff6a38182 in start_thread (arg=0x7fffe1835700) at pthread_create.c:312
#28 0x00007ffff071747d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Running electron 0.30.0 on ubuntu 14.04.

**Comment by zsalzbank** [comment]
This might be related to https://github.com/atom/electron/issues/2261.

**Comment by deepak1556** [comment]
@zsalzbank the sample link seems to be broken, does the intercpeted request involve redirects ?

**Comment by zsalzbank** [comment]
Sorry about that - I've updated the link and here it is too: https://gist.github.com/zsalzbank/505d3bda65318bae9740

From what I can tell, it does not - the javascript block involved loads google analytics from their servers.  When I make download the file locally and serve it that way, all is good.
