### ISSUE TITLE
Install Error "Cannot find module 'is-property'" 

### ISSUE THREAD

**Issue by basarat** [atom/electron#2319]
Ran `npm install electron-prebuilt -g` as suggested by readme.

Main log: 

```
C:\Users\bas\AppData\Roaming\npm\electron -> C:\Users\bas\AppData\Roaming\npm\node_modules\electron-prebuilt\cli.js

> electron-prebuilt@0.30.0 postinstall C:\Users\bas\AppData\Roaming\npm\node_modules\electron-prebuilt
> node install.js

module.js:334
    throw err;
          ^
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\bas\AppData\Roaming\npm\node_modules\electron-prebuilt\node_modules\electron-download\node_modules\nugget\node_modules\request\node_modules\har-validator\node_modul
es\is-my-json-valid\node_modules\generate-object-property\index.js:1:80)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\iojs\\node.exe" "C:\\Program Files (x86)\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-prebuilt" "-g"
npm ERR! node v2.3.0
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.30.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.30.0 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bas\npm-debug.log
```

Versions: 
```
C:\Users\bas>npm -v
2.11.1
C:\Users\bas>node -v
v2.3.0
```

The complete debug : https://gist.github.com/basarat/a913c77a711dedce111b

**Comment by zcbenz** [comment]
I have moved this issue to https://github.com/mafintosh/electron-prebuilt/issues/46.

**Comment by frankhale** [comment]
@basarat You may want to have a look at the same issue I posted to electron-prebuilt https://github.com/mafintosh/electron-prebuilt/issues/40

**Comment by thesbros** [comment]
Was also having this problem on my Windows VM, just update io.js and reinstall electron-prebuilt.
