### ISSUE TITLE
Linker error when using native addons

### ISSUE THREAD

**Issue by gerhardberger** [atom/electron#2344]
hi

I made an example app that used the Hello World addon example and it worked fine, but after some time it started throwing a linker error when I wanted to rebuild the addon. I can't say it surely but I think it started to throw the error after I updated to El Capitan beta 4 from beta 3.
I use this command to build the addon:
``` bash
HOME=~/.electron-gyp node-gyp rebuild --target=0.30.0 --arch=ia64 --dist-url=https://atom.io/download/atom-shell
```
now I get this error:
``` bash
...
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/binding/addon.o
  SOLINK_MODULE(target) Release/binding.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild" "--target=0.30.0" "--arch=ia64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /Users/gerhard/Desktop/example/elektron
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```
I checked and I have a `libgcc_s.10.5.tbd` file in my `/usr/lib` folder.

thanks

**Comment by zcbenz** [comment]
I saw the https://github.com/TooTallNate/node-gyp/issues/675 posted by you, and since your module can not compile when targeting for Node.js, I'm assuming this is not a bug of Electron.
