### ISSUE TITLE
How to do desktop notifications?

### ISSUE THREAD

**Issue by s-a** [atom/electron#2421]
Can some one point me to some docs how to realize cross platform desktop notifications? 
Seems http://www.w3.org/TR/notifications/ is available but does not show anything.

```javascript
// request permission on page load
document.addEventListener('DOMContentLoaded', function () {
  if (Notification.permission !== "granted"){
    Notification.requestPermission();
  }
});

function notify() {
  if (!Notification) {
    alert('Desktop notifications not available in your browser. Try Chromium.'); 
    return;
  }

  if (Notification.permission === "granted"){
	    var notification = new Notification('Notification title', {
	      icon: path.join(__dirname, "icon.jpg"),
	      body: "Hey there! You've been notified!",
	    });
		console.log("done");

	    notification.onclick = function () {
	      window.open("https://atom.io/");
	    };
  }
}

notify();
```

Since Chrome has its own rich notification system I wonder that this is not available in electron? 
 - http://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/extensions/docs/examples/api/notifications/
 - https://developer.chrome.com/apps/notifications
 - https://developer.chrome.com/apps/richNotifications

Tried to load this extension but it fails with weird syntax error:
https://developer.chrome.com/extensions/samples#search:notification%20demo

```
Error: Unexpected token /
SyntaxError: Unexpected token /
    at Object.parse (native)
    at getExtensionInfoFromPath (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\chrome-extension.js:32:21)
    at Function.BrowserWindow.addDevToolsExtension (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\chrome-extension.js:108:23)
    at callFunction (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\rpc-server.js:123:18)
    at EventEmitter.<anonymous> (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\rpc-server.js:219:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\web-contents.js:98:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
SyntaxError: Unexpected token /
    at Object.parse (native)
    at getExtensionInfoFromPath (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\chrome-extension.js:32:21)
    at Function.BrowserWindow.addDevToolsExtension (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\chrome-extension.js:108:23)
    at callFunction (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\rpc-server.js:123:18)
    at EventEmitter.<anonymous> (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\rpc-server.js:219:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\web-contents.js:98:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\api\lib\remote.js:98:15)
    at Function.RemoteMemberFunction (c:\git\iron-node\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\api\lib\remote.js:132:26)
    at boot (file:///C:/git/iron-node/app/app.js:175:13)
    at file:///C:/git/iron-node/app/app.js:238:1
```

**Comment by hokein** [comment]
The Notification API in Electron only works on OS X and sometimes on Linux. You can view a sample here: https://github.com/hokein/electron-sample-apps/tree/master/notifications.

**Comment by s-a** [comment]
Hmm...,  
I played around with node-notifier but it does not have an cooperate identity look over platforms and it is not that flashy as I wish on windows. I just thought why not simply create an own frame-less window and display this window bottom right? Thoughts?

**Comment by zcbenz** [comment]
Notifications on Windows is tracked at #262.
