### ISSUE TITLE
[Windows] test.py errors

### ISSUE THREAD

**Issue by etiktin** [atom/electron#2558]
When I run `test.py` on the clean master branch in Windows, I get 4 failures. 
Here's the failure summary:
```
passes: 223 failures: 4 duration: 19.00s

ipc module
remote.require
X should search module from the user app ‣
AssertionError: 'C:\\electron\\spec\\static\\main.js' == 'C:\\electron\\spec\\static\\main.js'
  at Context.<anonymous> (C:\electron\spec\api-ipc-spec.coffee:22:14)
  at callFn (C:\electron\spec\node_modules\mocha\lib\runnable.js:251:21)
  at Test.Runnable.run (C:\electron\spec\node_modules\mocha\lib\runnable.js:244:7)
  at Runner.runTest (C:\electron\spec\node_modules\mocha\lib\runner.js:374:10)
  at C:\electron\spec\node_modules\mocha\lib\runner.js:452:12
  at next (C:\electron\spec\node_modules\mocha\lib\runner.js:299:14)
  at C:\electron\spec\node_modules\mocha\lib\runner.js:309:7
  at next (C:\electron\spec\node_modules\mocha\lib\runner.js:248:23)
  at Immediate._onImmediate (C:\electron\spec\node_modules\mocha\lib\runner.js:276:5)
  at processImmediate [as _immediateCallback] (timers.js:371:17)

third-party module
runas
X can be required in renderer ‣
Error: The specified procedure could not be found.
C:\electron\spec\node_modules\runas\build\Release\runas.node
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
  at Module.load (C:\electron\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (C:\electron\spec\node_modules\runas\lib\runas.js:4:11)
  at Object.<anonymous> (C:\electron\spec\node_modules\runas\lib\runas.js:47:4)
  at Module._compile (module.js:430:26)
  at Object.Module._extensions..js (module.js:448:10)
  at Module.load (C:\electron\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Context.<anonymous> (C:\electron\spec\modules-spec.coffee:12:7)
  at callFn (C:\electron\spec\node_modules\mocha\lib\runnable.js:251:21)
  at Test.Runnable.run (C:\electron\spec\node_modules\mocha\lib\runnable.js:244:7)
  at Runner.runTest (C:\electron\spec\node_modules\mocha\lib\runner.js:374:10)
  at C:\electron\spec\node_modules\mocha\lib\runner.js:452:12
  at next (C:\electron\spec\node_modules\mocha\lib\runner.js:299:14)
  at C:\electron\spec\node_modules\mocha\lib\runner.js:309:7
  at next (C:\electron\spec\node_modules\mocha\lib\runner.js:248:23)
  at Immediate._onImmediate (C:\electron\spec\node_modules\mocha\lib\runner.js:276:5)
  at processImmediate [as _immediateCallback] (timers.js:371:17)

X can be required in node binary ‣
AssertionError: 'The specified procedure could not be found.\r\nC:\\electron\\spec\\node_modules\\runas\\build == 'ok'
  at ChildProcess.<anonymous> (C:\electron\spec\modules-spec.coffee:18:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at handleMessage (internal/child_process.js:632:10)
  at Pipe.channel.onread (internal/child_process.js:421:11)

<webview> tag
nodeintegration attribute
X loads native modules when navigation happens ‣
AssertionError: 'Uncaught Error: The specified procedure could not be found.\r\nC:\\electron\\spec\\node_modul == 'function'
  at webview.listener2 (C:\electron\spec\webview-spec.coffee:55:18)
  at WebViewImpl.dispatchEvent (C:\electron\out\D\resources\atom.asar\renderer\lib\web-view\web-view.js:143:31)
  at dispatchEvent (C:\electron\out\D\resources\atom.asar\renderer\lib\web-view\guest-view-internal.js:47:13)
  at EventEmitter.<anonymous> (C:\electron\out\D\resources\atom.asar\renderer\lib\web-view\guest-view-internal.js:58:30)
  at emitMany (events.js:108:13)
  at EventEmitter.emit (events.js:182:7)
```

Tested using Windows 8.1 64 bit with a 32 bit bootstrapped Electron.

**Comment by etiktin** [comment]
#2559 fixes the first error.

The 3 other errors are all related to `runas` not working correctly. 
I tried rebuilding `runas` cleanly by doing the following:
- Cleared npm's cache.
- Delete the node_modules folder under spec.
- Running bootstrap.py which reinstalled the modules. 

The build was successful (the log is available [here](https://gist.github.com/etiktin/1b3e44a114267dd3be7d)), but the tests still fail.

**Comment by zcbenz** [comment]
For the 3 failing specs it is actually expected. With current build model V8 is statically linked with node.dll under Release build, while dynamically linked under Debug build, so the native modules built against Release build can not be used under Debug build.

To make the tests pass you can run the them with Release build:

```cmd
$ ./script/test.py -R
```

Sorry I should have mentioned this in documents.

**Comment by etiktin** [comment]
@zcbenz, does this happen on all platforms?
Is it possible to build modules with the debug build? If so then, can we make `build.py -c D`, build it like that automatically?
Can we make `test.py`, ignore these tests when using Electron from the debug target?

I think it's important, especially in a collaborative projects, that tests will fail only if something is actually broken. Otherwise, developers will either start ignoring them (since they are used to tests failing), or waste time trying to figure out if they accidentally broke something when they didn't.

**Comment by zcbenz** [comment]
It is only happening on Windows because of how Windows search for symbols.

> Is it possible to build modules with the debug build? If so then, can we make build.py -c D, build it like that automatically?

It should be possible, but it is quite hard to do since node-gyp doesn't support specifying the location of `node.lib`.

> Can we make test.py, ignore these tests when using Electron from the debug target?

I think we should ignore those tests in Debug build.
