### ISSUE TITLE
[0.31.0] forking with --debug from renderer closes streams instantly

### ISSUE THREAD

**Issue by bpasero** [atom/electron#2562]
Trying out 0.31.0 I see an issue where my forked app (from the renderer) is quitting instantly as soon as I set its execArgv to --debug to be able to debug it. I verified that this does not happen in an earlier version of Electron (0.27.1):

**main.js**
```javascript
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var amainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when Eolectron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600, show: true});

  // and load the index.html of the app.
  mainWindow.loadUrl('file://' + __dirname + '/index.html');

  // Open the devtools.
  mainWindow.openDevTools();

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});
```

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello World!</title>
    <script src="./index.js">
    </script>
  </head>
  <body>
   
  </body>
</html>
```

**index.js**
```javascript
var cp = require("child_process");
var child = cp.fork(__dirname + "/app.js", [], {
  execArgv: ['--debug']
});

child.on('message', function (m) {
  console.log('[PARENT] got message:', m);
});

child.on('close', function () {
  console.log("CLOSED")
})

child.on('exit', function () {
  console.log("EXIT")
})
```

**app.js**
```javascript
process.on("message", function() {
	
})
```

The fact that app.js has a listener installed should let it keep running, but instead it closes.

**Comment by bpasero** [comment]
I see issues with cp.fork() when I try to run VS Code with the latest where my forked apps (from the renderer) crash instantly without much info. Having a hard time to reproduce this in a standalone app though. Is there something that could have an impact around forking either from the update to Chrome 44 or io.js 3.1.0?

**Comment by bpasero** [comment]
Stacks I am seeing:

[uncaught exception]:  Error: UnknownSystemError: Unknown system error, uv_pipe_open
    at Error (native)
    at new Socket (net.js:129:18)
    at createWritableStdioStream (node.js:601:18)
    at process.stderr (node.js:642:16)
    at Socket._destroy (net.js:464:25)
    at Socket.destroy (net.js:495:8)
    at maybeDestroy (net.js:420:12)
    at Pipe.onread (net.js:551:5)
