### ISSUE TITLE
vm.createContext crash on 0.32.x

### ISSUE THREAD

**Issue by tomashanacek** [atom/electron#2755]
**Electron Version:** 0.32.1
**System:** OS X 10.9.5

![electron](https://cloud.githubusercontent.com/assets/1244486/9785634/13843982-57b4-11e5-9333-eec99c67130c.png)

**Comment by deepak1556** [comment]
@zcbenz related upstream bug https://github.com/nodejs/node/pull/2091#issuecomment-118073326 and fix https://github.com/nodejs/node/commit/56db28b6d734dc397459f5cfee51cb41b370c30b

snippet to cause crash 
```
require('vm').runInNewContext('')
```

stacktrace
```
#0  0x00007ffff773a0f8 in v8::internal::Internals::GetNodeState(v8::internal::Object**) () from /home/robo/github/shell/out/D/libnode.so
#1  0x00007ffff777da1e in v8::PersistentBase<v8::Context>::IsWeak() const () from /home/robo/github/shell/out/D/libnode.so
#2  0x00007ffff777d97c in v8::Local<v8::Context> node::PersistentToLocal<v8::Context>(v8::Isolate*, v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> > const&) ()
   from /home/robo/github/shell/out/D/libnode.so
#3  0x00007ffff777c4c9 in node::ContextifyContext::context() const () from /home/robo/github/shell/out/D/libnode.so
#4  0x00007ffff777cb68 in node::ContextifyContext::GlobalPropertyGetterCallback(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&) ()
   from /home/robo/github/shell/out/D/libnode.so
#5  0x00007ffff70baf97 in v8::internal::PropertyCallbackArguments::Call(void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), v8::Local<v8::Name>) ()
   from /home/robo/github/shell/out/D/libv8.so
#6  0x00007ffff7360881 in v8::internal::JSObject::GetPropertyWithInterceptor(v8::internal::LookupIterator*, bool*) () from /home/robo/github/shell/out/D/libv8.so
#7  0x00007ffff7360527 in v8::internal::Object::GetProperty(v8::internal::LookupIterator*, v8::internal::LanguageMode) () from /home/robo/github/shell/out/D/libv8.so
#8  0x00007ffff73175f3 in v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) () from /home/robo/github/shell/out/D/libv8.so
#9  0x00007ffff731dbba in v8::internal::LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) () from /home/robo/github/shell/out/D/libv8.so
```
