### ISSUE TITLE
Failed to install `v8-debug`

### ISSUE THREAD

**Issue by scv119** [atom/electron#2833]
I am trying to install `v8-debug` for some package in Atom 1.0.15, which has electron version 0.30.6.
According to https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-npm-way, I use following command to build.
```
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.30.6
export npm_config_arch=x64
HOME=~/.electron-gyp npm install v8-debug@0.5.4
```

But I got following result with node v0.12.4, npm v2.10.1

```
chenshen@chenshen-mbp2:~$ HOME=~/.electron-gyp npm install v8-debug@0.5.4
-
> v8-debug@0.5.4 preinstall /Users/chenshen/node_modules/v8-debug
>

-
> v8-debug@0.5.4 install /Users/chenshen/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.6
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/chenshen/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/chenshen/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/chenshen/node_modules/v8-debug/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/chenshen/node_modules/v8-debug/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/chenshen/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/chenshen/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "node" "/Users/chenshen/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/chenshen/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok
Unsupported target version: 0.30.6
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "v8-debug@0.5.4"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.5.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.5.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support
```

**Comment by zcbenz** [comment]
Currently node modules rely on node-pre-gyp can not be built against electron, it is currently tracked at https://github.com/mapbox/node-pre-gyp/pull/112.

**Comment by scv119** [comment]
Thanks for the information!
