### ISSUE TITLE
Multiple possible failures during `bootstrap.py` execution due to poor connection

### ISSUE THREAD

**Issue by nantas** [atom/electron#2856]
Such as:

```bash
fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Could not resolve host: chromium.googlesource.com
Clone of 'https://chromium.googlesource.com/chromium/tools/depot_tools.git' into submodule path 'vendor/depot_tools' failed
```

```bash
Submodule path 'vendor/native_mate': checked out 'b7387da0854b20d376fdae0d93a01f83d080668d'
Cloning into 'vendor/node'...
remote: Counting objects: 171631, done.
remote: Compressing objects: 100% (3536/3536), done.
error: RPC failed; result=56, HTTP code = 200 MiB | 23.00 KiB/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Clone of 'https://github.com/atom/node.git' into submodule path 'vendor/node' failed
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 192, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 39, in main
    update_submodules()
  File "./script/bootstrap.py", line 85, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/Volumes/HD2/projects/electron/script/lib/util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
```

I think they are mostly caused by connection error. Recently connection from China are performing poorly. Is there any possibility to have electron bootstrap download from mirror in China?

**Comment by zcbenz** [comment]
The most reliable way is to setup global VPN, the project downloads things from S3, GitHub, Google servers, it is impossible to provide mirrors for all of them.
