### ISSUE TITLE
Failed to recurse into submodule path 'vendor/brightray'

### ISSUE THREAD

**Issue by zaaach** [atom/electron#3079]
git submodule update --init --recursive
fatal: reference is not a tree: 27ccc74468a444323f32dbe79219f049c9de9be6
Unable to checkout '27ccc74468a444323f32dbe79219f049c9de9be6' in submodule path 'vendor/brightray/vendor/libchromiumcontent'
Failed to recurse into submodule path 'vendor/brightray'
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 192, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 39, in main
    update_submodules()
  File "./script/bootstrap.py", line 85, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/ruxim/git/local/notes/electron/script/lib/util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1

**Comment by zcbenz** [comment]
It has been fixed on master branch now.
