### ISSUE TITLE
Cannot read property 'showItemInFolder' of undefined

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#3139]
I'm calling showItemInFolder from the renderer process
```javascript
require("shell").showItemInFolder(mypath);
```

It works successfully for a few numbers of calls (number not consistant), and then stop working.
Then I get the following error for all next calls: 
```
Uncaught Error: Cannot read property 'showItemInFolder' of undefined
TypeError: Cannot read property 'showItemInFolder' of undefined
    at EventEmitter.<anonymous> (C:\Users\Felicien\git\TweakStyle\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\lib\rpc-server.js:224:37)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (C:\Users\Felicien\git\TweakStyle\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\lib\web-contents.js:97:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by zcbenz** [comment]
Which operating system are you using?

**Comment by felicienfrancois** [comment]
Windows 10

**Comment by ducky427** [comment]
I've experienced this in Windows 8.1 as well.
