### ISSUE TITLE
Consistant renderer crash on windows from v0.33.9+

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#3191]
I get a consistent crash on windows 10 64bit (tested on 2 different machines).
It happen in my app when I close a tab and free a bunch of objects, possibly linked with others.

Please note that:
- There is no crash report sent, even if crash-reporter is setup in both main and renderer sides
- It does not happen on mac nor linux
- I get the crash on all versions from 0.33.9 to 0.34.1 but not on 0.33.8 and before.

#### How to reproduce
- Download [one of the distributions of my app](https://tweakstyle.com/download.html#all-downloads)
- Run the app.asar with a newer version of electron (v0.33.9 or greater)
- After the welcome screen, double click on index.html from the sample project
- In the newly created pane, open one of the files file by clicking on it
- Close the tab => Renderer Crash

**Comment by zcbenz** [comment]
I'm unable to run your app:

```
Uncaught Exception:
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at c (C:\cygwin\home\zcbenz\codes\electron\app.asar\tsmain.js:1:942)
    at C:\cygwin\home\zcbenz\codes\electron\app.asar\tsmain.js:1:597
    at C:\cygwin\home\zcbenz\codes\electron\app.asar\tsmain.js:1:2002
    at Server.onListen (C:\cygwin\home\zcbenz\codes\electron\app.asar\node_modules\portfinder\lib\portfinder.js:49:5)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at doNTCallback1 (node.js:430:9)
```

Can you see if there is any crash dump generated under `C:\Users\USERNAME\AppData\Local\Temp\APPNAME Crashes`? Also the `operation_log.txt` should be able to tell whether a crash dump has been generated and uploaded.

**Comment by felicienfrancois** [comment]
Sorry, to run the app, app.asar must be in a `resources` dir, because I do the following chdir at startup:
```
process.chdir(__dirname.replace(/[\\\/]resources[\\\/]app\.asar.*$/i, ""));
```

There is no dump in this directory, only `operation_log.txt`
Here is the last log entries:

```
[7280:8516:1023/224625:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://tweakstyle.com/php/crash-report.php --application-name=TweakStyle --v=1]
[7280:8516:1023/224625:VERBOSE1:crash_service.cc(142)] window handle is 000000000008083E
[7280:8516:1023/224625:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\TweakStyle Crash Service
dumps at C:\Users\Felicien\AppData\Local\Temp\TweakStyle Crashes
[7280:8516:1023/224625:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\Felicien\AppData\Local\Temp\TweakStyle Crashes\crash_checkpoint.txt
server is https://tweakstyle.com/php/crash-report.php
maximum 128 reports/day
reporter is electron-crash-service
[7280:8516:1023/224625:VERBOSE1:crash_service_main.cc(84)] Ready to process crash requests
[7280:8524:1023/224625:VERBOSE1:crash_service.cc(323)] client start. pid = 3084
[7280:8524:1023/224626:VERBOSE1:crash_service.cc(323)] client start. pid = 1340
[8432:8484:1023/224626:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=https://tweakstyle.com/php/crash-report.php --application-name=TweakStyle --v=1]
[8432:8484:1023/224626:VERBOSE1:crash_service.cc(142)] window handle is 0000000000040B8C
[8432:8484:1023/224626:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\TweakStyle Crash Service
dumps at C:\Users\Felicien\AppData\Local\Temp\TweakStyle Crashes
[8432:8484:1023/224626:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\Felicien\AppData\Local\Temp\TweakStyle Crashes\crash_checkpoint.txt
server is https://tweakstyle.com/php/crash-report.php
maximum 128 reports/day
reporter is electron-crash-service
[8432:8484:1023/224626:ERROR:crash_service.cc(301)] could not start dumper
[7280:6648:1023/224636:VERBOSE1:crash_service.cc(331)] client end. pid = 1340
[7280:6648:1023/224636:VERBOSE1:crash_service.cc(331)] client end. pid = 3084
[7280:6648:1023/224637:VERBOSE1:crash_service.cc(352)] zero clients. exiting
[7280:8516:1023/224637:VERBOSE1:crash_service.cc(490)] session ending..
[7280:8516:1023/224637:VERBOSE1:crash_service.cc(495)] clients connected :2
clients terminated :2
dumps serviced :0
dumps reported :0
[7280:8516:1023/224637:VERBOSE1:crash_service_main.cc(89)] Session end. return code is 0
```

I think the relevant line is `ERROR could not start dumper`

**Comment by zcbenz** [comment]
I didn't see a welcome screen so I just opened some random html files to test, but I didn't succeed to reproduce. You probably have to build Electron locally, and then use WinDbg or Visual Studio to get a full stack trace since the debugger is not working somehow.

**Comment by felicienfrancois** [comment]
I made more tests. I get the crash only with the x64 build of electron. The ia32 build is working fine.

Here is a quick capture of how to reproduce http://recordit.co/iIEOjH6nb7
Note: I open the html file with a double click

I'm trying to build electron to get the full stack, but I'm stuck with the following error at build step:
```
ninja: Entering directory `out\D'
[360/589] CXX obj\vendor\node\src\node.string_bytes.obj
c:\users\felicien\source\repos\electron\vendor\node\src\string_bytes.cc(191) : warning C4003: not enough actual parameters for macro 'V'
[377/589] CXX obj\atom\browser\ui\electron_lib.file_dialog_win.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\cl.exe" /nologo /showIncludes /FC @obj\atom\browser\ui\electron_lib.file_dialog_win.obj.rsp /c ..\..\atom\browser\ui\file_dialog_win.cc /Foobj\atom\browser\ui\electron_lib.file_dialog_win.obj /Fdobj\electron_lib.cc.pdb
c:\users\felicien\source\repos\electron\atom\browser\ui\file_dialog_win.cc(7) : fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory
[377/589] CXX obj\atom\browser\electron_lib.browser_win.obj
FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\cl.exe" /nologo /showIncludes /FC @obj\atom\browser\electron_lib.browser_win.obj.rsp /c ..\..\atom\browser\browser_win.cc /Foobj\atom\browser\electron_lib.browser_win.obj /Fdobj\electron_lib.cc.pdb
c:\users\felicien\source\repos\electron\atom\browser\browser_win.cc(7) : fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory
[377/589] CXX obj\atom\browser\electron_lib.web_view_manager.obj
ninja: build stopped: subcommand failed.
```

Not sure if it's a common error. I have visual studio 2013 Community

**Comment by felicienfrancois** [comment]
When I run it with a electron x64 debug build, I get the following error:
```
[6868:1029/112754:FATAL:crash_reporter_win.cc(130)] Check failed: RtlDeleteFunctionTable(&record->runtime_function).
```

**Comment by felicienfrancois** [comment]
Seems to be fixed in 0.34.2

May be related to 
> Fix crash when the callback passed to native APIs threw exception.

**Comment by felicienfrancois** [comment]
I reopen, as I still get the issue with 0.34.2.
I don't know why i don't get it last time

**Comment by felicienfrancois** [comment]
I successfully reproduced it with a vmware virtual machine, with both a fresh install of windows 10 64bit french and a fresh install of windows 7 64bit french.

I never got the crash report sent (nor dumped in the `C:\Users\USERNAME\AppData\Local\Temp\APPNAME Crashes` dir)
If I watch for webContent `crashed` event, I get it but without any relevant info.

I'm trying to debug it with visual studio, when attaching to all electron process, the breakpoint I get when it crash point to this: https://github.com/atom/electron/blob/d2b3d6d129ec0f1a4b06e5d6a3068dd01a11beba/atom/common/crash_reporter/crash_reporter_win.cc#L126-L131
Maybe it's the cause why the crash is not reported? But how do I access the cause of the crash?

Also, I could export the breakpoint if I knew how to but I'm not used to visual studio and I don't find this feature.

**Comment by zcbenz** [comment]
Can you disable the crash-reporter and then try debugging it with VS?

**Comment by felicienfrancois** [comment]
If I disable the crash-reporter, it no longer crashes.

I have just removed the crash-reporter init from the renderer code (i left it in the main code)
Here what I removed in a script included in the head of html:
```
require('crash-reporter').start({
	productName: 'MyProductName',
	companyName: 'MyCompany',
	submitUrl: 'https://mydomain.com/php/crash-report.php',
	autoSubmit: true
});
```

**Comment by felicienfrancois** [comment]
Also if I trigger crash with `process.crash()` on the renderer side, I successfully get the crash dump sent but I don't get the `webContents.crashed` event.

**Comment by felicienfrancois** [comment]
It may be related to #3276

**Comment by zcbenz** [comment]
Does it still crash if you replace this line:

```c++
CHECK(RtlDeleteFunctionTable(&record->runtime_function));
```

to

```c++
RtlDeleteFunctionTable(&record->runtime_function);
```

and then start the crash-reporter?

**Comment by felicienfrancois** [comment]
I confirm that It no longer crashes with this change

**Comment by zcbenz** [comment]
@felicienfrancois I think I have figured out why it crashed, thanks for debugging this!

**Comment by felicienfrancois** [comment]
You're welcome
Thank you for your work on electron
