### ISSUE TITLE
 possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by pcalin** [atom/electron#3244]
This error started happening again after upgrading yesterday.

I'm using nightmare js to run tests in electron.

(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at EventEmitter.<anonymous> (C:\code\DistributedDataDelivery\RWWA.Distribution\RWWA.Deployment\node_modules\nightmare\lib\runner.js:103:14)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at process.<anonymous> (C:\code\DistributedDataDelivery\RWWA.Distribution\RWWA.Deployment\node_modules\nightmare\lib\ipc.js:28:10)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
(node) warning: possible EventEmitter memory leak detected. 11 log listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at EventEmitter.<anonymous> (C:\code\DistributedDataDelivery\RWWA.Distribution\RWWA.Deployment\node_modules\nightmare\lib\runner.js:107:14)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at process.<anonymous> (C:\code\DistributedDataDelivery\RWWA.Distribution\RWWA.Deployment\node_modules\nightmare\lib\ipc.js:28:10)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by zcbenz** [comment]
This should be an issue of `nightmare`.
