### ISSUE TITLE
Issue with using selenium and webdriver doc

### ISSUE THREAD

**Issue by johnislarry** [atom/electron#3338]
I followed the document here:

https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md

using `selenium-webdriver`, but when I run a very simple version of the provided code:

```
var webdriver = require('selenium-webdriver');

var driver = new webdriver.Builder()
  // The "9515" is the port opened by chrome driver.
  .usingServer('http://localhost:9515')
  .withCapabilities({
    chromeOptions: {
      binary: '/usr/local/bin/atom'
    }
  })
  .forBrowser('electron')
  .build();

driver.quit();
```

And I let this run for about 30 seconds, I always get the error:

```
/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^
UnknownError: unknown error: Chrome failed to start: exited normally
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.0 x86_64)
    at new bot.Error (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at promise.Promise.goog.defineClass.invokeCallback_ (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:366:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at Builder.build (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/builder.js:445:22)
    at Object.<anonymous> (/Users/jonaldislarry/Projects/e2e/main.js:12:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
From: Task: WebDriver.quit()
    at webdriver.WebDriver.schedule (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)
    at webdriver.WebDriver.quit (/Users/jonaldislarry/Projects/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:445:21)
    at Object.<anonymous> (/Users/jonaldislarry/Projects/e2e/main.js:39:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

I'm wondering if somebody can maybe point me in the right direction here.... Much appreciated!

**Comment by zcbenz** [comment]
Starting with `/usr/local/bin/atom` is probably not going to work since Atom has its own ways of handling command line, can you try with your own app or a fresh downloaded binary?

**Comment by johnislarry** [comment]
I ended up going with the excellent [spectron](https://www.npmjs.com/package/spectron) package instead of this route.  I suspect the underlying issue with this was that the version of electron that atom was using was different than the one expected by the selenium package.  I'm going to close out this issue.  Thanks for your attention @zcbenz!
