### ISSUE TITLE
electron-rebuild could not rebuild serialport native module

### ISSUE THREAD

**Issue by Mirodil** [atom/electron#3439]
I have module `serialport@2.0.2` which builds sucessfuly with node-gyp but with `electron-rebuild` it gets the following error:
```
node_modules\.bin\electron-rebuild --module-dir app/node_modules
```
```
269 info install serialport@2.0.2
270 verbose unsafe-perm in lifecycle true
271 info serialport@2.0.2 Failed to exec install script
272 verbose stack Error: serialport@2.0.2 install: `node-pre-gyp install --fallback-to-build`
272 verbose stack Exit status 1
272 verbose stack     at EventEmitter.<anonymous> (d:\NodeJS\dcAlarm\node_modules\npm\lib\utils\lifecycle.js:214:16)
272 verbose stack     at emitTwo (events.js:87:13)
272 verbose stack     at EventEmitter.emit (events.js:172:7)
272 verbose stack     at ChildProcess.<anonymous> (d:\NodeJS\dcAlarm\node_modules\npm\lib\utils\spawn.js:24:14)
272 verbose stack     at emitTwo (events.js:87:13)
272 verbose stack     at ChildProcess.emit (events.js:172:7)
272 verbose stack     at maybeClose (internal/child_process.js:817:16)
272 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
273 verbose pkgid serialport@2.0.2
274 verbose cwd d:\NodeJS\dcAlarm\app\node_modules
275 error Windows_NT 6.1.7601
276 error argv "C:\\Program Files\\nodejs\\node.exe" "d:\\NodeJS\\dcAlarm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=0.34.3" "--arch=ia32"
277 error node v4.1.1
278 error npm  v2.14.11
279 error code ELIFECYCLE
280 error serialport@2.0.2 install: `node-pre-gyp install --fallback-to-build`
280 error Exit status 1
281 error Failed at the serialport@2.0.2 install script 'node-pre-gyp install --fallback-to-build'.
281 error This is most likely a problem with the serialport package,
281 error not with npm itself.
281 error Tell the author that this fails on your system:
281 error     node-pre-gyp install --fallback-to-build
281 error You can get their info via:
281 error     npm owner ls serialport
281 error There is likely additional logging output above.
282 verbose exit [ 1, true ]
```

**Comment by paulcbetts** [comment]
node-serialport is manually inlining an old version of node-pre-gyp, please file this bug on the serialport module
