### ISSUE TITLE
test.py intermittent fatal error on Windows 

### ISSUE THREAD

**Issue by etiktin** [atom/electron#3538]
Using [latest master](https://github.com/atom/electron/tree/29052b04986daf55ecda4163bb94adaf522d1a10), test.py fails intermittently with the following error:
```
[47776:1121/065616:FATAL:render_frame_host_impl.cc(1939)] Check failed: 
GetSiteInstance()->GetBrowserContext() == other_render_frame_host->GetSiteInstance()->
GetBrowserContext() (0AA3B0D8 vs. 0EB259D0)
Traceback (most recent call last):
  File "C:\electron\script\test.py", line 40, in <module>
    sys.exit(main())
  File "C:\electron\script\test.py", line 36, in main
    subprocess.check_call([atom_shell, 'spec'] + sys.argv[1:])
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\electron\\out\\D\\electron.exe', 'spec']' returned
non-zero exit status -2147483645
```
It happens about half the times. When it doesn't crash the result is usually that all tests passed.
I'm using Windows 8.1 64 bit.

**Comment by zcbenz** [comment]
I'm unable to produce the crash, and I never got a similar crash before, this is weird.

**Comment by etiktin** [comment]
Here's the log after I set `ELECTRON_ENABLE_STACK_DUMPING`:
```
[35516:1124/171705:FATAL:render_frame_host_impl.cc(1939)] Check failed: GetSiteInstance()->GetBrowserContext() == other_render_frame_host->GetSiteInstance()->GetBrowserContext() (0B662F28 vs. 14C85D90)
Backtrace:
        base::BigEndianWriter::remaining [0x0177AF11+142523]
        content::MediaStreamManager::Closed [0x02C2E245+2483819]
        content::MediaStreamManager::Closed [0x02C2BD96+2474428]
        content::MediaStreamManager::Closed [0x02A89BC2+761832]
        content::MediaStreamManager::Closed [0x02A999FF+826917]
        content::MediaStreamManager::Closed [0x02A91686+793260]
        ui::AXTreeSourceAdapter::IsEqual [0x0F7BED69+53656]
        content::MediaStreamManager::Closed [0x02A8BED0+770806]
        content::MediaStreamManager::Closed [0x02C2E7FC+2485282]
        content::MediaStreamManager::Closed [0x02C27F6F+2458517]
        content::MediaStreamManager::Closed [0x02C30C7F+2494629]
        content::MediaStreamManager::Closed [0x02DE6F06+4289324]
        IPC::BrokerableAttachment::~BrokerableAttachment [0x6CED7EB6+24727]
        IPC::BrokerableAttachment::~BrokerableAttachment [0x6CED851C+26365]
        base::BigEndianWriter::remaining [0x0177EA9F+157769]
        base::BigEndianWriter::remaining [0x017A7581+324395]
        base::BigEndianWriter::remaining [0x017A6A99+321603]
        base::BigEndianWriter::remaining [0x017A93FC+332198]
        base::BigEndianWriter::remaining [0x017A9F1D+335047]
        base::BigEndianWriter::remaining [0x017A7440+324074]
        content::MediaStreamManager::Closed [0x02B1C1E5+1361419]
        content::MediaStreamManager::Closed [0x02B1D7FA+1367072]
        content::MediaStreamManager::Closed [0x02B1769E+1342148]
        content::MediaStreamManager::Closed [0x02A4D01E+513092]
        content::MediaStreamManager::Closed [0x02A4CEAF+512725]
        content::MediaStreamManager::Closed [0x02A46DC3+487913]
        wWinMain [0x001EFD3F+1279] (c:\electron\atom\app\atom_main.cc:161)
        __tmainCRTStartup [0x0053DC0C+303] (f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c:618)
        BaseThreadInitThunk [0x765A7C04+36]
        RtlInitializeExceptionChain [0x77C8AD1F+143]
        RtlInitializeExceptionChain [0x77C8ACEA+90]
Traceback (most recent call last):
  File "C:\electron\script\test.py", line 40, in <module>
    sys.exit(main())
  File "C:\electron\script\test.py", line 36, in main
    subprocess.check_call([atom_shell, 'spec'] + sys.argv[1:])
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\electron\\out\\D\\electron.exe', 'spec']' returned non-zero exit status -2147483645
```
The check that throws, seems to come from [`RenderFrameHostImpl::IsSameSiteInstance`](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/frame_host/render_frame_host_impl.cc&q=render_frame_host_impl.cc&sq=package:chromium&l=2084).

Before it happens, when the tests are around 44%, the application is stuck until a timeout is fired and a dialog is displayed asking me if I want to "Keep Waiting", I choose to keep waiting and the tests continue. The failed tests at this stage are:
```
passes: 198 failures: 2 duration: 238.61s
session module
DownloadItem
can download successfully ‣
Error: timeout of 10000ms exceeded
  at done (C:\electron\spec\node_modules\mocha\lib\runnable.js:206:67)
  at C:\electron\spec\node_modules\mocha\lib\runnable.js:227:9
  at EventEmitter.<anonymous> (C:\electron\spec\api-session-spec.coffee:105:11)
  at EventEmitter.g (events.js:260:16)
  at emitMany (events.js:108:13)
  at EventEmitter.emit (events.js:182:7)
"after each" hook ‣
Error: timeout of 10000ms exceeded
  at done (C:\electron\spec\node_modules\mocha\lib\runnable.js:206:67)
  at callFn (C:\electron\spec\node_modules\mocha\lib\runnable.js:262:7)
  at Hook.Runnable.run (C:\electron\spec\node_modules\mocha\lib\runnable.js:244:7)
  at next (C:\electron\spec\node_modules\mocha\lib\runner.js:259:10)
  at Immediate._onImmediate (C:\electron\spec\node_modules\mocha\lib\runner.js:276:5)
  at processImmediate [as _immediateCallback] (timers.js:374:17)
chromium feature
heap snapshot
sending request of http protocol urls
document.hidden
navigator.webkitGetUserMedia
navigator.language
window.open
window.opener
window.opener.postMessage
```
Around 88% Electron crashes with the fatal error.

@zcbenz, do you have an idea what might have caused this? If not, I guess we can just leave it open for a while and see if anyone else encounters this issue.

**Comment by zcbenz** [comment]
@etiktin Can you try whether latest master branch work?

**Comment by etiktin** [comment]
It works with the current master (https://github.com/atom/electron/commit/9a707b7c69cb0d1a78dfcc56c8e0978f142acc56). Thanks!
