### ISSUE TITLE
ENOENT, no such file or directory: path.txt

### ISSUE THREAD

**Issue by codevigilante** [atom/electron#3563]
Trying to use electron-prebuilt following this:

npm install -g electron-prebuilt --save-dev

On npm start get this:

```javascript

> unruled@0.0.0 start /Users/.../Dropbox/dev/Electron/UnruledFN
> electron .


fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/.../Dropbox/dev/Electron/UnruledFN/node_modules/electron-prebuilt/path.txt'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (/Users/.../Dropbox/dev/Electron/UnruledFN/node_modules/electron-prebuilt/index.js:4:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/.../Dropbox/dev/Electron/UnruledFN/node_modules/electron-prebuilt/cli.js:3:16)
npm ERR! weird error 8
npm ERR! not ok code 0

```

path.txt isn't in node_modules/electron-prebuilt/ and I have no idea what's supposed to be in it.

Looks like I'm using Electron 0.35.1

**Comment by paulcbetts** [comment]
Don't install with `-g`

**Comment by zcbenz** [comment]
I suggest reporting this to https://github.com/mafintosh/electron-prebuilt.
