### ISSUE TITLE
64bit Build error

### ISSUE THREAD

**Issue by tonny-zhang** [atom/electron#3654]
I was in trouble compiling the 64bit (32bit build success), Here is build output: 
```
$ /d/soft/Python27_2.7.3/python /f/source/git_projects/electron_list/electron_2
0151201/script/build.py -c R
ninja: Entering directory `out\R'
[1/24] LINK_EMBED(DLL) node.dll
FAILED: d:\soft\Python27_2.7.3\python.exe gyp-win-tool link-with-manifests envir
onment.x64 True node.dll "d:\soft\Python27_2.7.3\python.exe gyp-win-tool link-wr
apper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node
.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.
manifest" obj\vendor\node\node.node.dll.generated.manifest
v8_base_0.lib(v8_base_0.api.obj) : fatal error LNK1112: module machine type 'X86
' conflicts with target machine type 'x64'
Traceback (most recent call last):
  File "gyp-win-tool", line 316, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 169, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "d:\soft\Python27_2.7.3\lib\subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'd:\soft\Python27_2.7.3\python.exe gyp-wi
n-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib
/DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit s
tatus 1112
ninja: build stopped: subcommand failed.
```

My operating system is `windows7 64bit`, `electron` version is `0.35.2`, `node` version is `v4.2.2`, 

Thanks very much for your help.

**Comment by zcbenz** [comment]
I think you are somehow building with the 32bit binaries of libchromiumcontent, you can cleanup everything with `./script/clean.py` and then try again.

**Comment by tonny-zhang** [comment]
@zcbenz yes, I build 64bit after building 32bit and got the error.

Proposed to put this solution into [build-instructions-windows.md](https://github.com/atom/electron/blob/master/docs/development/build-instructions-windows.md), believe that there are a lot of people like me care it.

@zcbenz thanks again!
