### ISSUE TITLE
bootstrap failed on Windows if checkout by tag v0.35.4

### ISSUE THREAD

**Issue by sanfilip** [atom/electron#3736]
I am trying to checkout and build electron by tag v0.35.4 on Windows 10 with Python 2.7.10, Git 1.9.5, and VS2013 installed.
The whole process works fine if I am checking out HEAD.

```
C:\Users\Tom>git clone -b v0.35.4 https://github.com/atom/electron.git
Cloning into 'electron'...
remote: Counting objects: 42814, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 42814 (delta 52), reused 0 (delta 0), pack-reused 42705
Receiving objects: 100% (42814/42814), 12.04 MiB | 4.61 MiB/s, done.
Resolving deltas: 100% (30875/30875), done.
Checking connectivity... done.
Note: checking out 'e1d7ef7e24affd8f4ede3689c5354ef11036bf62'.

C:\Users\Tom>cd electron

C:\Users\Tom\electron>python script\bootstrap.py -v
Running in verbose mode
git submodule sync
git submodule update --init --recursive
...
Cloning into 'vendor/native_mate'...
remote: Counting objects: 421, done.
remote: Compressing objects: 100% (4/4), done.
Receiving objects:  84% (354/421)   ote: Total 421 (delta 0), reused 0 (delta 0), pack-reused 417
Receiving objects: 100% (421/421), 105.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (298/298), done.
Checking connectivity... done.
Submodule path 'vendor/native_mate': checked out '5e70868fd0c005dc2c43bea15ca6e93da0b68741'
Cloning into 'vendor/node'...
remote: Counting objects: 179050, done.
remote: Compressing objects: 100% (6403/6403), done.
remote: Total 179050 (delta 2889), reused 0 (delta 0), pack-reused 172486
Receiving objects: 100% (179050/179050), 126.28 MiB | 4.83 MiB/s, done.
Resolving deltas: 100% (138008/138008), done.
Checking connectivity... done.
fatal: reference is not a tree: 1445826ca73cc79bc57d503dd11d4ffaf695625c
Cloning into 'vendor/requests'...
remote: Counting objects: 16115, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 16115 (delta 0), reused 0 (delta 0), pack-reused 16110
Receiving objects: 100% (16115/16115), 6.70 MiB | 4.78 MiB/s, done.
Resolving deltas: 100% (9139/9139), done.
Checking connectivity... done.
Submodule path 'vendor/requests': checked out 'e4d59bedfd3c7f4f254f4f5d036587bcd8152458'
Unable to checkout '1445826ca73cc79bc57d503dd11d4ffaf695625c' in submodule path 'vendor/node'
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 210, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 39, in main
    update_submodules()
  File "script\bootstrap.py", line 95, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\Users\Tom\electron\script\lib\util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit
status 1
```

I also tried v0.35.2 and had the same issue.
There was a similar issue back in July, #2086

**Comment by rosca** [comment]
It happens on both mac and windows for fresh clones. It looks like the node commits used in Electron v0.34.* and v0.35.* got orphaned (1445826ca73cc79bc57d503dd11d4ffaf695625c and edfbc29d09425f2f387c52d77f6351b6ce101659). The situation described here: https://help.github.com/articles/commit-exists-on-github-but-not-in-my-local-clone/.

Could you please raise this in priority?

**Comment by zcbenz** [comment]
Sorry for the trouble, I forgot to tag the commit before resetting the tree, it should now.

**Comment by rosca** [comment]
Thanks.

**Comment by sanfilip** [comment]
Yes, thank you!  Those builds work for me now.
