### ISSUE TITLE
[0.36.1] <browser-win>.webContents.session.cookies.remove throwing error

### ISSUE THREAD

**Issue by kamesh-a** [atom/electron#3860]
Hello,

While executing our test codes. clearing cookies test case was failing in 0.36.1,  Attached the sample stack trace. 

```
Error: Could not call remote function `remove`. Check that the function signature is correct. Underlying error: Error processing argument -1.
Error: Could not call remote function `remove`. Check that the function signature is correct. Underlying error: Error processing argument -1.
    at callFunction (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:186:13)
    at EventEmitter.<anonymous> (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:281:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:101:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at callFunction (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:186:13)
    at EventEmitter.<anonymous> (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:281:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:101:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:108:15)
    at RemoteMemberFunction [as remove] (/Applications/electron-v0.36.1-darwin-x64/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:142:26)
    at Object.util.cookies._delete (<anonymous>:6:45)

```
Env : 

Electron : 0.36.1 
Mac :  OS x El captain 

Works fine in : 0.36.0

**Comment by deepak1556** [comment]
That denotes argument type mismatch, might have missed the api change `cookies.remove(<object>, callback)` => `cookies.remove(url, name, callback)`

**Comment by zcbenz** [comment]
Sorry I accidentally introduced a breaking API change in #3789, you need to use the new API signature now. I'll change the code to be compatible with the old API.

**Comment by kamesh-a** [comment]
@deepak1556  and @zcbenz  thanks for letting me know there is change. I didn't see the signature. should have given a look into coffee script source :+1:
