### ISSUE TITLE
Error: IPC channel is already disconnected

### ISSUE THREAD

**Issue by felixcrive** [atom/electron#3994]
Running Nightmare (2.1.2) with electron-prebuilt (0.36.2) I got this error

```javascript
Debug: internal, implementation, error 
    Error: IPC channel is already disconnected
    at ChildProcess.target.disconnect (internal/child_process.js:631:26)
    at Nightmare.done (/Users/fcguerrero/Public/work/myrpoject/node_modules/nightmare/lib/nightmare.js:222:17)
    at Nightmare.next (/Users/fcguerrero/Public/work/myrpoject/node_modules/nightmare/lib/nightmare.js:204:28)
    at EventEmitter.<anonymous> (/Users/fcguerrero/Public/work/myrpoject/node_modules/nightmare/lib/nightmare.js:214:12)
    at EventEmitter.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at EventEmitter.emit (events.js:166:7)
    at ChildProcess.<anonymous> (/Users/fcguerrero/Public/work/myrpoject/node_modules/nightmare/lib/ipc.js:28:10)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
```

Any ideas what cause this error? Thanks.

**Comment by zcbenz** [comment]
This is a client side error, caused by calling `disconnect` to a already disconnected process. You can debug into Nightmare to find out why it happened.

**Comment by serv** [comment]
@felixcrive Hey I'm having the same issue on both Mac OSX and CentOS. Did you get a solve for the issue?

**Comment by felixcrive** [comment]
@serv I haven't, apparently is a Nightmare bug, but if you find something please keep me posted. Thanks.
