### ISSUE TITLE
MenuItem ReadOnly Property `type`

### ISSUE THREAD

**Issue by niftylettuce** [atom/electron#4097]
When you try to change a menu items `type`, it won't let you... how do you?

```log
Uncaught Exception:
TypeError: Cannot assign to read only property 'type' of [object Object]
    at /Users/bazfoo/Public/foobar/src/menu-builder.js:299:21
    at Array.map (native)
    at MenuBuilder.buildMenu (/Users/bazfoo/Public/foobar/src/menu-builder.js:296:15)
    at EventEmitter.<anonymous> (/Users/bazfoo/Public/foobar/src/index.js:56:8)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by zcbenz** [comment]
Menu item's type can not be changed, you have to recreate one if you want to change its type.
