### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by theniceboy** [atom/electron#4130]
I installed electron-prebuilt using the command `npm install -g electron-prebuilt` and ran the app using the command `electron .`, and then this error showed up (I didn't even see the main window):
````
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/David/Github/Johnston/main.js:34:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:252:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
````
Is there any solution?

**Comment by zcbenz** [comment]
As the error mean, a JavaScript error occurred in your `main.js`.
