### ISSUE TITLE
require tries to load wrong binding of sqlite3

### ISSUE THREAD

**Issue by Malgalad** [atom/electron#4176]
So, uh, the infamous problem with sqlite3, I guess. Another one.

OS Win10 x64, node 5.4.1, electron 0.36.4, sqlite3 3.1.1, sequelize 3.17.3.

I am using `sequelize` to manage sqlite database. I added both `sequelize` and `sqlite3` to *externals* option of webpack. The problem is, when I try to launch application, the error appears:
```
Error: The dialect sqlite is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite. (Error: Please install sqlite3 package manually)
```
I rebuilt native modules as was suggested in docs and numerous Internet answers, but the problem persisted. So I investigated further, and, ultimately, found that error appears in `sequelize\lib\dialects\sqlite\connection-manager.js:25`, specifically
```
try {
  this.lib = require(sequelize.config.dialectModulePath || 'sqlite3').verbose();
} catch (err) {
  throw new Error('Please install sqlite3 package manually');
}
```
Logging this `err`, I got the true problem:
```
 A dynamic link library (DLL) initialization routine failed.
\\?\C:\PATH_TO_PROJECT\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:162:18)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:162:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\PATH_TO_PROJECT\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at new ConnectionManager (C:\PATH_TO_PROJECT\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:25:16)
```
Apparently it tries to load sqlite3 for node.js. However! I double checked and, expectedly, found directory `sqlite3\lib\binding\electron-v0.36-win32-x64` with `node_sqlite3.node` inside.

So electron (?) tries to `require` node binding instead of electron's even though it exists. I am fairly new to electron and binding of native modules, anyone can hint how to resolve this issue? How to make `require` require one binding over the other?

**Comment by Malgalad** [comment]
Never mind, problem with `node-pre-gyp package`. https://github.com/mapbox/node-pre-gyp/issues/189#issuecomment-173426428
