### ISSUE TITLE
Can't build on Winodws - release branch 0.36.5

### ISSUE THREAD

**Issue by wangzhen263** [atom/electron#4196]
I tried to build electron release branch 0.36.5 on windows 7 x64. 

Script runs in `VS2013 x64 Native Tools Command Prompt`.
this is error log.
```powershell
Download directxsdk-x64     1806291  [100.0%]
Download vs2012-crt-x64      774046  [100.0%]
Traceback (most recent call last):
  File "vendor\brightray\vendor\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "C:\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", line 5
45, in script_main
    return main(sys.argv[1:])
  File "C:\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", line 5
38, in main
    return gyp_main(args)
  File "C:\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\__init__.py", line 5
23, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Python27\lib\site-packages\gyp-0.1-py2.7.egg\gyp\generator\ninja.py",
 line 2415, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Python27\lib\multiprocessing\pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 528, in get
    raise self._value
AssertionError: 'C:/develop/electron/vendor/brightray/vendor/download/libchromiu
mcontent/src/content/app' can not be absolute path (see crbug.com/462153).
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 210, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 51, in main
    run_update()
  File "script\bootstrap.py", line 206, in run_update
    execute_stdout([sys.executable, update])
  File "C:\develop\electron\script\lib\util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\develo
p\\electron\\script\\update.py']' returned non-zero exit status 1

C:\develop\electron>python script\bootstrap.py -v --target_arch=x64
```

My environment is 
python v2.7.3
node v0.12.9
git v1.8.3.msysgit.0
VC community 2013 sp4

**Comment by zcbenz** [comment]
According to the log you have installed `gyp` locally:

```
C:\Python27\lib\site-packages\gyp-0.1-py2.7.egg\
```

You need to remove it otherwise it is going to override the one used in Electron.

**Comment by wangzhen263** [comment]
Thanks @zcbenz. Works for me.
