### ISSUE TITLE
hideInternalModules() throws error

### ISSUE THREAD

**Issue by DerNivel** [atom/electron#4219]
When calling `require('electron').hideInternalModules();` in the main process (not tested in renderer process), it throws an error.

```
Uncaught Exception:
TypeError: require(...).hideInternalModules is not a function
    at Object.<anonymous> (PRIVATE_PATH\build\browser\bootstrap.js:4:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (PRIVATE_PATH\node_modules\electron-prebuilt\dist\resources\default_app\main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

Electron Version: 0.36.5

**Comment by zcbenz** [comment]
You must have the npm `electron` module installed somewhere in your system, which overrides the builtin electron module. You can find out the path of it by logging out `require.resolve('electron')`.

**Comment by DerNivel** [comment]
I don't have the npm `electron` module installed!
`require.resolve('electron')` throws `Error: Cannot find module 'electron'`

**Comment by zcbenz** [comment]
Interesting, it seems to be broken in recent versions.
