### ISSUE TITLE
Error: Failed to set path

### ISSUE THREAD

**Issue by tymat** [atom/electron#4434]
Error Message:

```
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/init.js:136:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
```

Version Information:

```
$ npm view electron-prebuilt

{ name: 'electron-prebuilt',
  description: 'Install electron (formerly called atom-shell) prebuilt binaries for command-line use using npm',
  'dist-tags': { latest: '0.36.7' },
  versions:
   [ '0.24.0',
     '0.25.0',
     '0.25.1-1',
     '0.25.1',
     '0.25.2-1',
     '0.25.2',
     '0.25.3-1',
     '0.25.3-2',
     '0.25.3',
     '0.26.0',
     '0.26.1',
     '0.27.0',
     '0.27.1',
     '0.27.2',
     '0.27.3',
     '0.28.0',
     '0.28.1',
     '0.28.2',
     '0.28.3',
     '0.29.0',
     '0.29.1',
     '0.29.2',
     '0.30.0',
     '0.30.1',
     '0.30.2',
     '0.30.3',
     '0.30.4',
     '0.30.5',
     '0.30.6',
     '0.30.7',
     '0.30.8',
     '0.31.0',
     '0.31.1',
     '0.31.2',
     '0.32.0',
     '0.32.1',
     '0.32.2',
     '0.32.3',
     '0.33.0',
     '0.33.1',
     '0.33.2',
     '0.33.3',
     '0.33.4',
     '0.33.5',
     '0.33.6',
     '0.33.7',
     '0.33.8',
     '0.33.9',
     '0.34.0',
     '0.34.1',
     '0.34.2',
     '0.34.3',
     '0.34.4',
     '0.34.5',
     '0.35.0',
     '0.35.1',
     '0.35.2',
     '0.35.3',
     '0.35.4',
     '0.35.5',
     '0.35.6',
     '0.36.0',
     '0.36.1',
     '0.36.2',
     '0.36.3',
     '0.36.4',
     '0.36.5',
     '0.36.6',
     '0.36.7' ],
  maintainers:
   [ 'maxogden <max@maxogden.com>',
     'mafintosh <mathiasbuus@gmail.com>',
     'zcbenz <zcbenz@gmail.com>',
     'mattdesl <dave.des@gmail.com>' ],
  time:
   { modified: '2016-01-30T07:08:43.886Z',
     created: '2015-04-17T18:20:15.972Z',
     '0.24.0': '2015-04-17T18:20:15.972Z',
     '0.25.0': '2015-04-25T19:50:04.796Z',
     '0.25.1': '2015-04-25T19:50:35.828Z',
     '0.25.1-1': '2015-04-30T09:41:18.103Z',
     '0.25.2': '2015-05-03T14:53:06.437Z',
     '0.25.2-1': '2015-05-08T22:18:36.952Z',
     '0.25.3': '2015-05-08T22:19:57.893Z',
     '0.25.3-1': '2015-05-10T20:54:47.018Z',
     '0.25.3-2': '2015-05-10T20:56:00.078Z',
     '0.26.0': '2015-05-13T00:22:18.646Z',
     '0.26.1': '2015-05-22T03:16:08.372Z',
     '0.27.0': '2015-05-28T18:16:55.057Z',
     '0.27.1': '2015-05-28T18:17:17.027Z',
     '0.27.2': '2015-06-01T22:38:33.151Z',
     '0.27.3': '2015-06-09T18:13:52.153Z',
     '0.28.0': '2015-06-15T16:37:52.230Z',
     '0.28.1': '2015-06-15T16:38:19.643Z',
     '0.28.2': '2015-06-19T18:00:36.254Z',
     '0.28.3': '2015-06-23T07:40:10.155Z',
     '0.29.0': '2015-07-03T11:16:31.592Z',
     '0.29.1': '2015-07-03T16:21:13.693Z',
     '0.29.2': '2015-07-07T10:07:01.632Z',
     '0.30.0': '2015-07-16T17:56:21.985Z',
     '0.30.1': '2015-07-24T10:36:40.875Z',
     '0.30.2': '2015-07-30T06:57:18.420Z',
     '0.30.3': '2015-08-07T14:48:10.852Z',
     '0.30.4': '2015-08-10T15:36:18.628Z',
     '0.30.5': '2015-08-21T05:51:08.196Z',
     '0.31.0': '2015-08-21T13:07:50.664Z',
     '0.30.6': '2015-08-26T08:40:03.048Z',
     '0.31.1': '2015-08-28T05:57:39.243Z',
     '0.31.2': '2015-09-02T06:12:49.787Z',
     '0.32.0': '2015-09-09T05:06:26.863Z',
     '0.32.1': '2015-09-09T12:26:44.064Z',
     '0.32.2': '2015-09-12T16:50:53.954Z',
     '0.32.3': '2015-09-15T08:27:37.567Z',
     '0.33.0': '2015-09-17T11:39:26.071Z',
     '0.33.1': '2015-09-22T08:04:00.200Z',
     '0.30.7': '2015-09-24T07:23:52.444Z',
     '0.33.2': '2015-09-25T12:32:48.493Z',
     '0.30.8': '2015-09-26T14:04:32.464Z',
     '0.33.3': '2015-09-26T14:39:29.302Z',
     '0.33.4': '2015-10-02T06:14:59.451Z',
     '0.33.5': '2015-10-05T04:46:58.040Z',
     '0.33.6': '2015-10-05T13:13:37.483Z',
     '0.33.7': '2015-10-10T11:16:05.144Z',
     '0.33.8': '2015-10-14T05:23:56.708Z',
     '0.33.9': '2015-10-16T10:37:00.905Z',
     '0.34.0': '2015-10-16T12:16:45.456Z',
     '0.34.1': '2015-10-23T13:52:43.904Z',
     '0.34.2': '2015-10-30T07:34:05.027Z',
     '0.34.3': '2015-11-06T15:56:42.354Z',
     '0.35.0': '2015-11-16T11:08:29.280Z',
     '0.35.1': '2015-11-20T07:01:48.868Z',
     '0.34.4': '2015-11-24T14:24:19.716Z',
     '0.34.5': '2015-11-28T20:26:06.790Z',
     '0.35.2': '2015-11-28T20:26:28.231Z',
     '0.35.3': '2015-12-04T09:50:18.522Z',
     '0.35.4': '2015-12-04T12:39:19.575Z',
     '0.36.0': '2015-12-11T07:49:56.921Z',
     '0.36.1': '2015-12-18T07:17:38.212Z',
     '0.36.2': '2015-12-25T07:19:43.828Z',
     '0.35.5': '2015-12-31T05:02:27.248Z',
     '0.36.3': '2016-01-08T07:41:53.301Z',
     '0.35.6': '2016-01-11T06:30:34.927Z',
     '0.36.4': '2016-01-15T08:09:59.144Z',
     '0.36.5': '2016-01-22T15:47:49.632Z',
     '0.36.6': '2016-01-29T06:32:43.042Z',
     '0.36.7': '2016-01-30T07:08:43.886Z' },
  homepage: 'https://github.com/mafintosh/electron-prebuilt',
  repository:
   { type: 'git',
     url: 'git+https://github.com/mafintosh/electron-prebuilt.git' },
  author: 'Mathias Buus',
  bugs: { url: 'https://github.com/mafintosh/electron-prebuilt/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users:
   { sbruchmann: true,
     '9joneg': true,
     niksudan: true,
     tristanb: true,
     'joshua.marquez': true,
     noswap: true,
     joaocunha: true,
     windhamdavid: true,
     despairblue: true,
     preco21: true,
     kce001: true,
     ovrmrw: true,
     abdihaikal: true,
     matiasmarani: true,
     eerne: true,
     marlongrape: true },
  version: '0.36.7',
  scripts:
   { 'cache-clean': 'rm -rf ~/.electron && rm -rf dist',
     postinstall: 'node install.js',
     pretest: 'npm run cache-clean && node install.js',
     test: 'standard && tape test/*.js' },
  bin: { electron: 'cli.js' },
  main: 'index.js',
  dependencies: { 'extract-zip': '^1.0.3', 'electron-download': '^1.0.0' },
  devDependencies:
   { 'home-path': '^0.1.1',
     'path-exists': '^1.0.0',
     standard: '^5.4.1',
     tape: '^3.0.1' },
  dist:
   { shasum: 'b228bc643c85bed21df8071b8e45fcf480aa7eed',
     tarball: 'http://registry.npmjs.org/electron-prebuilt/-/electron-prebuilt-0.36.7.tgz' },
  directories: {} }
```

OS Version:

```
OS X El Capitan 10.11.3 (15D21)
```

**Comment by zcbenz** [comment]
This is because you don't have write access to `~/Library/Application Support/Electron` somehow, you can solve this by either fixing the permission issue, or just remove that directory.

**Comment by tymat** [comment]
Nope that doesn't seem to be the case:

```
aeufemio at kingmob in ~/Library/Application Support/Electron
$ ls -tlra
total 0
drwxr-xr-x@ 45 aeufemio  staff  1530 Feb 15 22:33 ..
-rw-r--r--   1 aeufemio  staff     0 Feb 15 22:34 test
drwxr-xr-x   3 aeufemio  staff   102 Feb 15 22:34 .
```

**Comment by zcbenz** [comment]
Can you try removing that directory?

**Comment by owenayres** [comment]
Just like to leave my two cents incase anyone has the same issue.

> I had this problem and the issue was because of special/not-allowed characters inside the name property of my app's package.json file. 

Inside my package.json file for my app (that is bundled with the app source), the name property had a colon inside it. This was causing this exact issue. Removing the colon from the name stopped this issue from happening and launched the app normally again.
