### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden (libchromiumcontent) - bootstrapping on FreeBSD

### ISSUE THREAD

**Issue by AnyCPU** [atom/electron#4476]
Same issue like on Windows https://github.com/atom/electron/issues/1687

`/usr/local/bin/python /users/dev/proj/ext/electron/vendor/brightray/script/bootstrap --commit ad63d8ba890bcaad2f1b7e6de148b7992f4d3af7 --target_arch x64 https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent
Downloading libchromiumcontent.zip...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/freebsd/x64/ad63d8ba890bcaad2f1b7e6de148b7992f4d3af7/libchromiumcontent.zip
Traceback (most recent call last):
  File "/users/dev/proj/ext/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 187, in <module>
    sys.exit(main())
  File "/users/dev/proj/ext/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 68, in main
    args.force)
  File "/users/dev/proj/ext/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 133, in download_if_needed
    download(destination, base_url, commit, filename)
  File "/users/dev/proj/ext/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 143, in download
    download_and_extract(destination, url)
  File "/users/dev/proj/ext/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 156, in download_and_extract
    with contextlib.closing(urllib2.urlopen(url)) as u:
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/users/dev/proj/ext/electron/vendor/brightray/script/bootstrap", line 106, in <module>
    sys.exit(main())
  File "/users/dev/proj/ext/electron/vendor/brightray/script/bootstrap", line 39, in main
    args.libcc_static_library_path)
  File "/users/dev/proj/ext/electron/vendor/brightray/script/bootstrap", line 94, in setup_libchromiumcontent
    subprocess.check_call([sys.executable, download, '-s'] + args)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/users/dev/proj/ext/electron/vendor/brightray/vendor/libchromiumcontent/script/download', '-s', '-f', '-c', 'ad63d8ba890bcaad2f1b7e6de148b7992f4d3af7', '--target_arch', 'x64', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', '/users/dev/proj/ext/electron/vendor/brightray/vendor/download/libchromiumcontent']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 210, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 44, in main
    args.libcc_static_library_path)
  File "./script/bootstrap.py", line 121, in bootstrap_brightray
    execute_stdout([sys.executable, bootstrap] + args)
  File "/users/dev/proj/ext/electron/script/lib/util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/users/dev/proj/ext/electron/vendor/brightray/script/bootstrap', '--commit', 'ad63d8ba890bcaad2f1b7e6de148b7992f4d3af7', '--target_arch', 'x64', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent']' returned non-zero exit status 1`

**Comment by zcbenz** [comment]
Building on FreeBSD is not supported currently, I'm merging this to #3797.
