### ISSUE TITLE
unable to run node-speaker in Electron (on windows)

### ISSUE THREAD

**Issue by MathijsvVelde** [atom/electron#4659]
* Electron version: v0.36.9
* Operating system: Windows 10 Pro x64

I cloned [Node-Speaker](https://github.com/TooTallNate/node-speaker.git), ran `npm install` in it's folder.
(Output:)
```cmd
$ npm install

> speaker@0.2.6 install ..\node-speaker
> node-gyp rebuild


..\node-speaker>if not defined npm_config_node_gyp (node "C:\Users\[User]\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win32.c
  win_delay_load_hook.c
  output.vcxproj -> ..\node-speaker\build\Release\\liboutput.lib
  binding.cc
  win_delay_load_hook.c
     Creating library ..\node-speaker\build\Release\binding.lib and object ..\node-speaker\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> ..\node-speaker\build\Release\\binding.node
npm WARN speaker@0.2.6 No license field.
```

When I test it running `$ node examples/sine.js`, it works fine.
When I test it running `$ electron examples/sine.js`, I get this error:
```cmd
Error
 A dynamic link library (DLL) initialization routine failed.
\\?\..\node-speaker\build\Release\binding.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (..\node-speaker\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (..\node-speaker\index.js:9:38)
```

:sob:
Am I doing something wrong?
I also tested it on Mac and Linux and it works fine there
So can you help me with this bug?

Thanks...

**Comment by enlight** [comment]
`node-speaker` relies on a native Node module, you need to rebuild native module to target Electron, as [explained in the docs](https://github.com/atom/electron/blob/v0.36.9/docs/tutorial/using-native-node-modules.md).

**Comment by MathijsvVelde** [comment]
unfortunately that does not help.
It is also an other error then what you get when you are running the wrong build...
more ideas maybe?

**Comment by enlight** [comment]
What doesn't help? What did you try? What errors did you get?

**Comment by MathijsvVelde** [comment]
rebuilding with 'electron-rebuild' doesn't help
I tried it on the 'node-speaker' module it self and on a project with the 'node-speaker' dependency
and I got the same errors

**Comment by kevinsawicki** [comment]
This looks similar to https://github.com/atom/node-spellchecker/issues/18 which seemed to be resolved via targeting a specific visual studio version.

Perhaps you want to try what this comment mentions https://github.com/atom/node-spellchecker/issues/18#issuecomment-128350864

**Comment by MathijsvVelde** [comment]
:cry: It didn't work for me...
this is what I did
notes :

1. I installed NodeJs @ c:\nodejs.
2. I updated npm globally to the most recent version with `npm install npm -g`
3. I have Visual Studio Community 2015 version 14.0.24720.00 Update 1 installed.
4. I use the latest python 2.7.10 version.
5. I ran `npm install -g node-gyp --msvs_version=2015`
6. and ran `npm uninstall speaker; npm install speaker`
7. finally I ran `node-gyp rebuild --target=0.30.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell`

But then I got a new error:
```terminal
C:\>node-gyp rebuild --target=0.30.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.7.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\LeMe\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\LeMe\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\LeMe\\.node-gyp\\0.30.2\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\LeMe\\.node-gyp\\0.30.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\LeMe\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\LeMe\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\LeMe\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.30.2" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```
Probably due to the "Atom Shell" no longer exist and that we now use "Electron"...

So can you help me fix this or can you provide me with a alternative "step 7"?

**Comment by MathijsvVelde** [comment]
Okay, I was in the wrong folder... Oops!
But it still didn't work.
I even tried these for step 7:
1. `node-gyp rebuild --target=5.7.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell`
2. `node-gyp rebuild`
3. `npm rebuild`
4. `npm rebuild --msvs_version=2015`

But still the same error...:sob:

**Comment by paulcbetts** [comment]
You need VS2013 to compile against Electron

**Comment by MathijsvVelde** [comment]
same results...
:cry: 
I got the old error again:
```
Error
 A dynamic link library (DLL) initialization routine failed.
\\?\..\node-speaker\build\Release\binding.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (..\node-speaker\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (..\node-speaker\index.js:9:38)
```

**Comment by MathijsvVelde** [comment]
BTW
```https://atom.io/download/atom-shell``` is outdated

**Comment by MathijsvVelde** [comment]
After many tries, I got a new error: :angry:

After executing the following commands:
```
$ cd C:\Users\IEUser\Documents\melome_player\app\node_modules\speaker
$ HOME=~/.electron-gyp node-gyp rebuild --target=0.37.5 --msvs_version=2013 --arch=ia32 --dist-url=https://atom.io/download/atom-shell

$ electron examples\sine.js
- or -
$ cd C:\Users\IEUser\Documents\melome_player\app
$ electron .
```
I got this error:
```
Error: %1 is not a valid Win32 application.

\\?\C:\Users\IEUser\Documents\melome_player\app\node_modules\speaker\build\Release\binding.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (C:\Users\IEUser\Documents\melome_player\app\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\IEUser\Documents\melome_player\app\node_modules\speaker\index.js:8:34)
``` 

When I execute:
```
$ cd C:\Users\IEUser\Documents\melome_player\app\node_modules\speaker
$ HOME=~/.electron-gyp node-gyp rebuild --target=0.37.5 --msvs_version=2013 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```
I get the old error...

Can someone try this for me on their win10 (x64) system?
I don't know what I am doing wrong.... :sob: 
just install 'electron-prebuilt' global `npm install -g electron-prebuilt`
install 'node-speaker' somewhere `npm install speaker` or git-clone it [Git:node-speaker](https://github.com/TooTallNate/node-speaker.git)

rebuild away! 

and then run `$ electron examples\sine.js`.
It should generating a 440.0 hz sine wave for 2 seconds

and then please tell me how you did it, in the smallest detail if you can

Thanks!!!
