### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir ...

### ISSUE THREAD

**Issue by rokyed** [atom/electron#4717]
##### Error: ENOENT: no such file or directory, scandir './app/language'
 is the message I recieve on the packaged app, but not in the prebuilt version, for this line of code:
https://github.com/rokyed/cocoChanelJS/blob/master/app/core/language-manager.js#L10

my related files are in this folder:
https://github.com/rokyed/cocoChanelJS/tree/master/app/language

I have tried the following paths:
``` javascript
'./language'
'./app/language'
'../language'

// P.S. in the first link the value of:
window['CCJS-MAIN-URLS'].app.language = './app/language'; // tested and confirmed
```

none are working.

My task is to load my language files no matter how many they are, but the packaged version won't cooperate.

Thanks for the solution, if any. I tried everything I had in mind and nothing....
If the path is totally different , what is that path and why ?

P.S. The prebuilt version works flawlessly, but the packaged version nope :cry: 
I am more than glad to hear from you!! 

* Electron version: v0.36.10
* Operating system: darwin x64  (OSX)

**Comment by kevinsawicki** [comment]
Are the files present in the `.app` for your packaged app?

The working directory used for relative paths by the `fs` APIs might be different for your packaged app versus running with `electron-prebuilt`.

You might want to use something absolute like `path.join(__dirname, 'app', 'language')` assuming the file you are setting `window['CCJS-MAIN-URLS'].app.language` is a parent of your `app` folder.

**Comment by rokyed** [comment]
OMG , Thank you soooo much !! It literally resolved the problem!!!

**Comment by kevinsawicki** [comment]
> It literally resolved the problem!!!

Glad to hear it, closing this out :+1:

**Comment by SebastianGuerreroCardenas** [comment]
I am having this issue, but in the packaged version the main.js is still next to the the folder that I am trying to read into.

**Comment by joshuaobinna** [comment]
Error: ENOENT: no such file or directory, scandir '.\dist\routes\api'
    at Object.readdirSync (fs.js:806:3)
    at importer (C:\Users\Joshua Osuji\New folder\Desktop\repo-template\node_modules\keystone\lib\core\importer.js:32:6)
    at eval (webpack:///./server.js?:29:8)
    at Module../server.js (C:\Users\Joshua Osuji\New folder\Desktop\repo-template\dist\server.js:97:1)
    at __webpack_require__ (C:\Users\Joshua Osuji\New folder\Desktop\repo-template\dist\server.js:20:30)
    at C:\Users\Joshua Osuji\New folder\Desktop\repo-template\dist\server.js:84:18
    at Object.<anonymous> (C:\Users\Joshua Osuji\New folder\Desktop\repo-template\dist\server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
[nodemon] app crashed - waiting for file changes before starting...
