### ISSUE TITLE
Error: renderer/api/lib/remote.js not found in atom.asar

### ISSUE THREAD

**Issue by 1dot75cm** [atom/electron#4778]
* Electron version: 0.36.11, 0.37.0
* Operating system: Fedora 23

After testing, the `electron 0.36.10` is work fine,
![electron 0.36.10](http://pic.fdzh.org/uploads/2016/03/2016_03_13 06_35_23 的屏幕截图.png)

 but `electron 0.36.11` return following errors.
```
$ ELECTRON_ENABLE_LOGGING=1 electron n1-build/Nylas/resources/app/ 
Streaming log data to /tmp/Nylas-N1-28087.log
[28087:0313/061553:ERROR:browser_main_loop.cc(253)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
App load time: 1333ms
[28087:0313/061554:INFO:CONSOLE(318)] "Error: ENOENT, renderer/api/lib/remote.js not found in /usr/lib64/electron/resources/atom.asar
    at notFoundError (ATOM_SHELL_ASAR.js:110:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:435:9)
    at compileFileAtPath (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/compile-cache.js:78:23)
    at Object.defineProperty.value [as .js] (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/compile-cache.js:203:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at handleSetupError (file:///home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/static/index.js:20:23)
    at window.onload (file:///home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/static/index.js:111:5)", source: /home/test/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (318)
[28087:0313/061554:INFO:CONSOLE(114)] "Uncaught Error: ENOENT, renderer/api/lib/remote.js not found in /usr/lib64/electron/resources/atom.asar", source: ATOM_SHELL_ASAR.js (114)
[28087:0313/061554:INFO:CONSOLE(340)] "Uncaught TypeError: Cannot read property 'getPluginIdsByPathBase' of null", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (340)
[28087:0313/061554:INFO:CONSOLE(318)] "Error: ENOENT, renderer/api/lib/remote.js not found in /usr/lib64/electron/resources/atom.asar
    at notFoundError (ATOM_SHELL_ASAR.js:110:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:435:9)
    at compileFileAtPath (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/compile-cache.js:78:23)
    at Object.defineProperty.value [as .js] (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/compile-cache.js:203:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at handleSetupError (file:///home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/static/index.js:20:23)
    at window.onload (file:///home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/static/index.js:111:5)", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (318)
[28087:0313/061555:INFO:CONSOLE(114)] "Uncaught Error: ENOENT, renderer/api/lib/remote.js not found in /usr/lib64/electron/resources/atom.asar", source: ATOM_SHELL_ASAR.js (114)
[28087:0313/061555:INFO:CONSOLE(340)] "Uncaught TypeError: Cannot read property 'getPluginIdsByPathBase' of null", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (340)
[28087:0313/061555:INFO:CONSOLE(318)] "TypeError: Cannot read property 'dispatch' of null
    at [object Object].jQuery.fn.trigger (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/space-pen-extensions.js:76:26)
    at jQuery.extend.ready (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/node_modules/space-pen/vendor/jquery.js:402:23)", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (318)
[28087:0313/061555:INFO:CONSOLE(76)] "Uncaught TypeError: Cannot read property 'dispatch' of null", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/space-pen-extensions.js (76)
[28087:0313/061555:INFO:CONSOLE(340)] "Uncaught TypeError: Cannot read property 'getPluginIdsByPathBase' of null", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (340)
[28087:0313/061555:INFO:CONSOLE(318)] "TypeError: Cannot read property 'dispatch' of null
    at [object Object].jQuery.fn.trigger (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/space-pen-extensions.js:76:26)
    at jQuery.extend.ready (/home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/node_modules/space-pen/vendor/jquery.js:402:23)", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (318)
[28087:0313/061555:INFO:CONSOLE(76)] "Uncaught TypeError: Cannot read property 'dispatch' of null", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/space-pen-extensions.js (76)
[28087:0313/061555:INFO:CONSOLE(340)] "Uncaught TypeError: Cannot read property 'getPluginIdsByPathBase' of null", source: /home/test/rpmbuild/BUILD/N1/n1-build/Nylas/resources/app/src/nylas-env.js (340)/
```

The path should be `/renderer/api/remote.js` instead of `renderer/api/lib/remote.js`.
```
$ asar l /usr/lib64/electron/resources/atom.asar|grep remote
/renderer/api/remote.js
```

**Comment by zcbenz** [comment]
Does the default app work?

**Comment by 1dot75cm** [comment]
Yes, default app is work.

**Comment by 1dot75cm** [comment]
Very nice, I fixed it. Thank you.

```
$ vim /usr/lib64/nylas/src/module-cache.js
// rendererRoot = path.join(electronRoot, 'renderer', 'api', 'lib');
rendererRoot = path.join(electronRoot, 'renderer', 'api');
```
