### ISSUE TITLE
menu.buildFromTemplate fails when accelerator is undefined

### ISSUE THREAD

**Issue by felicienfrancois** [atom/electron#4839]
* Electron version: 0.37.2
* Operating system: Windows 10

When calling menu.buildFromTemplate from the renderer:
```javascript
var remote = require('remote');
var menu = require('menu');
menu.buildFromTemplate([{
    label: "Test",
    accelerator: undefined
}]);
```

I get the following error:
```
...\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\a…:170 Uncaught Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Cannot assign to read only property 'accelerator' of object '#<MenuItem>'
Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Cannot assign to read only property 'accelerator' of object '#<MenuItem>'
    at callFunction (...\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\rpc-server.js:238:11)
    at EventEmitter.<anonymous> (...\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\rpc-server.js:319:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (...\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at callFunction (...\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\rpc-server.js:238:11)
    at EventEmitter.<anonymous> (...\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\rpc-server.js:319:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (...\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (...\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\api\remote.js:170:13)
    at remoteMemberFunction [as buildFromTemplate] (...\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\api\remote.js:110:18)
    at <anonymous>:2:35
    at Object.InjectedScript._evaluateOn (<anonymous>:878:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluate (<anonymous>:667:21)
```

Here a usecase:
```
function createMenuTemplate(label, action, accelerator) {
    return {
        label: label,
        click: action,
        accelerator: accelerator
    };
}
createMenuTemplate('Action without accelerator', function doSomething() {});
```

**Comment by zcbenz** [comment]
Closed with #4840.
