### ISSUE TITLE
Error compiling v8-profiler

### ISSUE THREAD

**Issue by HR** [atom/electron#4881]
* Electron version: 0.37.2
* Operating system: OSX 10.11.3

I'm receiving the following error when I try to compile the v8-profiler with node-pre-gyp
```shell
$ node_modules/.bin/node-pre-gyp --target=0.37.2 --runtime=electron --fallback-to-build --directory node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell reinstall
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.17
node-pre-gyp info using node@5.6.0 | darwin | x64
node-pre-gyp info chdir node_modules/v8-profiler/
node-pre-gyp info check checked for "/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64/profiler.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.6.0/electron-v0.37-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.6.0/electron-v0.37-darwin-x64.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://node-inspector.s3.amazonaws.com/profiler/v5.6.0/electron-v0.37-darwin-x64.tar.gz (falling back to source compile with node-gyp) 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | darwin | x64
gyp WARN chdir node_modules/v8-profiler/ is not a directory
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/HR/GitHub/project/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/HR/GitHub/project/node_modules/v8-profiler/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/HR/GitHub/project/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/HR/.node-gyp/0.37.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/HR/.node-gyp/0.37.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/HR/GitHub/project/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/HR/GitHub/project/node_modules/v8-profiler',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.6.0 | darwin | x64
gyp WARN chdir node_modules/v8-profiler/ is not a directory
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/profiler/src/profiler.o
In file included from ../src/profiler.cc:2:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/HR/GitHub/project/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/HR/.nvm/versions/node/v5.6.0/bin/node" "/Users/HR/GitHub/project/node_modules/node-gyp/bin/node-gyp.js" "build" "--target=0.37.2" "--runtime=electron" "--fallback-to-build" "--directory=node_modules/v8-profiler/" "--dist-url=https://atom.io/download/atom-shell" "--module=/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64"
gyp ERR! cwd /Users/HR/GitHub/project/node_modules/v8-profiler
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/HR/.nvm/versions/node/v5.6.0/bin/node /Users/HR/GitHub/project/node_modules/node-gyp/bin/node-gyp.js build --target=0.37.2 --runtime=electron --fallback-to-build --directory=node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell --module=/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/HR/GitHub/project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.3.0
node-pre-gyp ERR! command "/Users/HR/.nvm/versions/node/v5.6.0/bin/node" "/Users/HR/GitHub/project/node_modules/.bin/node-pre-gyp" "--target=0.37.2" "--runtime=electron" "--fallback-to-build" "--directory" "node_modules/v8-profiler/" "--dist-url=https://atom.io/download/atom-shell" "reinstall"
node-pre-gyp ERR! cwd /Users/HR/GitHub/project/node_modules/v8-profiler
node-pre-gyp ERR! node -v v5.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
Failed to execute '/Users/HR/.nvm/versions/node/v5.6.0/bin/node /Users/HR/GitHub/project/node_modules/node-gyp/bin/node-gyp.js build --target=0.37.2 --runtime=electron --fallback-to-build --directory=node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell --module=/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/HR/GitHub/project/node_modules/v8-profiler/build/profiler/v5.6.0/electron-v0.37-darwin-x64' (1)
```

**Comment by zcbenz** [comment]
Electron 0.37 is using V8 4.9, it seems that v8-profiler is not compatible with V8 4.9.

**Comment by framerate** [comment]
Since the directions here: http://electron.atom.io/docs/v0.37.7/tutorial/debugging-main-process/#make-sure-you-have-node-gyp-required-toolsnode-gyp-required-tools-installed don't work, with the current V8 is there anything else we can do to be debugging a crashing electron install?

Asking for myself and so if anyone else finds this issue like I did the answer is posted.

**Comment by ejfrancis** [comment]
I'm seeing this same error myself after following the [official documentation's steps](http://electron.atom.io/docs/tutorial/debugging-main-process/) and it's blocking me from being able to debug the main process

node 6.2.2
electron 1.3.5
v8-debug 0.7.7
v8-profiler 5.6.5


```
 node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-debug/ --dist-url=https://atom.io/download/atom-shell reinstall && node_modules/.bin/node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell reinstall

[v8-debug] Removing "/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-debug/build/debug/v0.7.7/electron-v1.3-darwin-x64"
node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/debug/v0.7.7/electron-v1.3-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and electron@1.3.5 (electron-v1.3 ABI) (falling back to source compile with node-gyp)
gyp WARN chdir node_modules/v8-debug/ is not a directory
2016-09-12 13:49:55.441 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.linux.x86_64.gcc.4.0.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:55.442 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d34a7330:'org.cocotron.1.0.linux.x86_64.gcc.4.0.1':Default>
2016-09-12 13:49:55.450 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecificationClang:0x7fa7d0db7030:'org.cocotron.1.0.linux.x86_64.notllvmgcc.4.2.1':Default>
2016-09-12 13:49:55.451 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.linux.i386.gcc.4.0.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_0'
2016-09-12 13:49:55.452 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d0e40270:'org.cocotron.1.0.linux.i386.gcc.4.0.1':Default>
2016-09-12 13:49:55.453 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.linux.i386.gcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:55.453 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d0e50ca0:'org.cocotron.1.0.linux.i386.gcc.4.2.1':Default>
2016-09-12 13:49:55.456 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.linux.x86_64.gcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:55.457 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d34fa8f0:'org.cocotron.1.0.linux.x86_64.gcc.4.2.1':Default>
2016-09-12 13:49:55.459 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecificationClang:0x7fa7d3610b60:'org.cocotron.1.0.linux.i386.notllvmgcc.4.2.1':Default>
2016-09-12 13:49:55.461 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.linux.i386.fakellvmgcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.llvmgcc42'
2016-09-12 13:49:55.462 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d0e5f0c0:'org.cocotron.1.0.linux.i386.fakellvmgcc.4.2.1':Default>
2016-09-12 13:49:55.463 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.solaris2.10.sparc.gcc.4.0.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:55.463 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d0e673d0:'org.cocotron.1.0.solaris2.10.sparc.gcc.4.0.1':Default>
2016-09-12 13:49:55.470 xcodebuild[24348:2211128] warning: compiler '::org.cocotron.1.0.linux.x86_64.fakellvmgcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.llvmgcc42'
2016-09-12 13:49:55.471 xcodebuild[24348:2211128] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7fa7d0ea0840:'org.cocotron.1.0.linux.x86_64.fakellvmgcc.4.2.1':Default>
gyp WARN chdir node_modules/v8-debug/ is not a directory
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:38:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        v8::Debug::Call(fn);
                   ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8-debug.h:201:37: note: 'Call' has been explicitly marked deprecated here
                       Local<Value> Call(v8::Local<v8::Function> fun,
                                    ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
../src/debug.cc:46:45: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                            ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8-debug.h:260:39: note: 'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext());
                                      ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
../src/debug.cc:61:51: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                  ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8-debug.h:260:39: note: 'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext());
                                      ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
../src/debug.cc:66:38: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
          debug_context = v8::Debug::GetDebugContext();
                                     ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8-debug.h:260:39: note: 'GetDebugContext' has been explicitly marked deprecated here
                static Local<Context> GetDebugContext());
                                      ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
4 warnings generated.
  CXX(target) Release/obj.target/debug/src/InjectedScriptHost.o
../src/InjectedScriptHost.cc:173:44: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> constructor = object->GetRealNamedProperty(constructorSymbol);
                                           ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8.h:2925:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
1 warning generated.
  SOLINK_MODULE(target) Release/debug.node
  COPY /Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-debug/build/debug/v0.7.7/electron-v1.3-darwin-x64/debug.node
  TOUCH Release/obj.target/action_after_build.stamp
node-pre-gyp ERR! Tried to download: https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/electron-v1.3-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and electron@1.3.5 (electron-v1.3 ABI) (falling back to source compile with node-gyp)
gyp WARN chdir node_modules/v8-profiler/ is not a directory
2016-09-12 13:49:59.499 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.linux.x86_64.gcc.4.0.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:59.500 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b3223d0:'org.cocotron.1.0.linux.x86_64.gcc.4.0.1':Default>
2016-09-12 13:49:59.508 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecificationClang:0x7ff11b48ee10:'org.cocotron.1.0.linux.x86_64.notllvmgcc.4.2.1':Default>
2016-09-12 13:49:59.509 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.linux.i386.gcc.4.0.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_0'
2016-09-12 13:49:59.509 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b16c100:'org.cocotron.1.0.linux.i386.gcc.4.0.1':Default>
2016-09-12 13:49:59.511 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.linux.i386.gcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:59.511 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b17cac0:'org.cocotron.1.0.linux.i386.gcc.4.2.1':Default>
2016-09-12 13:49:59.514 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.linux.x86_64.gcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:59.515 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b2c3d20:'org.cocotron.1.0.linux.x86_64.gcc.4.2.1':Default>
2016-09-12 13:49:59.517 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecificationClang:0x7ff11b1a37b0:'org.cocotron.1.0.linux.i386.notllvmgcc.4.2.1':Default>
2016-09-12 13:49:59.519 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.linux.i386.fakellvmgcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.llvmgcc42'
2016-09-12 13:49:59.520 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b2de840:'org.cocotron.1.0.linux.i386.fakellvmgcc.4.2.1':Default>
2016-09-12 13:49:59.520 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.solaris2.10.sparc.gcc.4.0.1' is based on missing compiler 'default::com.apple.compilers.gcc.4_2'
2016-09-12 13:49:59.521 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b1ac030:'org.cocotron.1.0.solaris2.10.sparc.gcc.4.0.1':Default>
2016-09-12 13:49:59.528 xcodebuild[24517:2211641] warning: compiler '::org.cocotron.1.0.linux.x86_64.fakellvmgcc.4.2.1' is based on missing compiler 'default::com.apple.compilers.llvmgcc42'
2016-09-12 13:49:59.529 xcodebuild[24517:2211641] warning:  multiple definitions of property 'USE_HEADERMAP' in <XCCompilerSpecification:0x7ff11b2f4990:'org.cocotron.1.0.linux.x86_64.fakellvmgcc.4.2.1':Default>
gyp WARN chdir node_modules/v8-profiler/ is not a directory
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
../src/heap_profiler.cc:35:18: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
        TryCatch try_catch;
                 ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8.h:6777:40: note: 'TryCatch' has been explicitly marked deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
                                       ^
/Users/username/.node-gyp/iojs-1.3.5/deps/v8/include/v8config.h:336:3: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
1 warning generated.
  CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
../src/heap_snapshot.cc:46:46: error: no member named 'GetHiddenValue' in 'v8::Object'
      info.GetReturnValue().Set(info.This()->GetHiddenValue(__root));
                                ~~~~~~~~~~~  ^
../src/heap_snapshot.cc:50:20: error: no member named 'SetHiddenValue' in 'v8::Object'
      info.This()->SetHiddenValue(__root, _root);
      ~~~~~~~~~~~  ^
2 errors generated.
make: *** [Release/obj.target/profiler/src/heap_snapshot.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/username/devel/DEVGRU/Atlas-Web/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/username/.nvm/versions/node/v6.2.2/bin/node" "/Users/username/devel/DEVGRU/Atlas-Web/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--target=1.3.5" "--runtime=electron" "--fallback-to-build" "--directory=node_modules/v8-profiler/" "--dist-url=https://atom.io/download/atom-shell" "--module=/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler/build/profiler/v5.6.5/electron-v1.3-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler/build/profiler/v5.6.5/electron-v1.3-darwin-x64"
gyp ERR! cwd /Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/username/.nvm/versions/node/v6.2.2/bin/node /Users/username/devel/DEVGRU/Atlas-Web/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --target=1.3.5 --runtime=electron --fallback-to-build --directory=node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell --module=/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler/build/profiler/v5.6.5/electron-v1.3-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler/build/profiler/v5.6.5/electron-v1.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/username/devel/DEVGRU/Atlas-Web/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/username/.nvm/versions/node/v6.2.2/bin/node" "/Users/username/devel/DEVGRU/Atlas-Web/node_modules/.bin/node-pre-gyp" "--target=1.3.5" "--runtime=electron" "--fallback-to-build" "--directory" "node_modules/v8-profiler/" "--dist-url=https://atom.io/download/atom-shell" "reinstall"
node-pre-gyp ERR! cwd /Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute '/Users/username/.nvm/versions/node/v6.2.2/bin/node /Users/username/devel/DEVGRU/Atlas-Web/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --target=1.3.5 --runtime=electron --fallback-to-build --directory=node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell --module=/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler/build/profiler/v5.6.5/electron-v1.3-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/username/devel/DEVGRU/Atlas-Web/node_modules/v8-profiler/build/profiler/v5.6.5/electron-v1.3-darwin-x64' (1)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/username/.nvm/versions/node/v6.2.2/bin/node" "/Users/username/.nvm/versions/node/v6.2.2/bin/npm" "run" "build-node-inspector"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 build-node-inspector: `node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-debug/ --dist-url=https://atom.io/download/atom-shell reinstall && node_modules/.bin/node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell reinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.10.0 build-node-inspector script 'node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-debug/ --dist-url=https://atom.io/download/atom-shell reinstall && node_modules/.bin/node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell reinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-debug/ --dist-url=https://atom.io/download/atom-shell reinstall && node_modules/.bin/node-pre-gyp --target=1.3.5 --runtime=electron --fallback-to-build --directory node_modules/v8-profiler/ --dist-url=https://atom.io/download/atom-shell reinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by enlight** [comment]
`v8-profiler` doesn't work with Electron v1.3.0+ due to breaking changes in the V8 API. I've documented a workaround at http://vadim.macagon.com/blog/2016/09/11/rebuilding-node-inspector-for-electron-v13x/ but it's a bit tedious, so I'm contemplating publishing a Node module to make it easier to deal with this.

**Comment by ejfrancis** [comment]
@enlight having that as an npm module would be really helpful for me

**Comment by enlight** [comment]
@ejfrancis OK, I've started working on it, I'll let you know when it's ready.

**Comment by enlight** [comment]
@ejfrancis I've just published [`electron-inspector`](https://github.com/enlight/electron-inspector) on NPM.
