### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by taroxd** [atom/electron#4977]
* Electron version: every version later than 0.36.7 (excluding 0.36.7)
* Operating system:
Windows 10 x64 build 10586

I do not know why I get this exception every time. Stack trace is as follows:
```
path\to\my\app\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\api\remote.js:170 Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
  at ObjectsRegistry.get (path\to\my\app\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\objects-registry.js:44:28)
  at EventEmitter.<anonymous> (path\to\my\app\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\rpc-server.js:318:31)
  at emitMany (events.js:108:13)
  at EventEmitter.emit (events.js:182:7)
  at EventEmitter.<anonymous> (path\to\my\app\node_modules\electron-prebuilt\dist\resources\atom.asar\browser\api\web-contents.js:136:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
```

**Comment by Petah** [comment]
Did you figure this out?

**Comment by lichaozhy** [comment]
Me too

**Comment by taroxd** [comment]
The bug described in this issue was fixed months ago. I think your issues are not related to this issue.
